### ISSUE TITLE
게스트 로그인 기능

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#10]
# 게스트 로그인
- 게스트는 멤버가 되기 위해 깃허브 계정으로 로그인을 한다.🌟

## 정상 케이스
- given: 깃허브에서 유효한 계정으로 로그인을 할 때
- when: 로그인을 한다
- then: 멤버로 등록이 되고 로그인이 된다.

## 깃허브 로그인이 실패한 케이스
- given: 깃허브 로그인이 실패했을 때
- when: 로그인을 한다
- then: 에러메시지를 출력한다.

**Comment by gracefulBrown** [comment]
### oauth 프로세스 참고 자료
![image](https://user-images.githubusercontent.com/46308949/118203019-1e37ce80-b496-11eb-84e6-d3d22cd2a4a2.png)

**Comment by pkeugine** [comment]
### [210516][백엔드][피케이, 소롱] 깃허브를 통한 로그인

* 클라이언트로부터 받은 코드로 깃허브에 access token 요청
* access token으로 다시 깃허브에 사용자 정보 요청
* 요청 이용하여 토큰 생성 후 클라이언트에게 토큰 전달

### 앞으로 남은 부분
* DB에 사용자 정보 저장 후 재로그인시 비교
* 토큰 payload에 우리 서비스 id 추가
* 로그인 실패 상황 고려
* 멤버 정보 요청에 응답

**Comment by soulgchoi** [comment]
- 더미 api 추가 #38

**Comment by pkeugine** [comment]
### [210519][백엔드][피케이, 소롱] 깃허브를 통한 로그인
* DB에 사용자 정보 저장 후 재로그인시 비교
* 토큰 payload에 우리 서비스 id 추가
* 로그인 실패 상황 고려
### 앞으로 남은 부분
* 멤버 정보 요청에 응답
