### ISSUE TITLE
백엔드 문서화 테스트 개선

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#1004]

**Comment by her0807** [comment]
헉 탐나네요

**Comment by Wishoon** [comment]
헉 저도..

**Comment by Yboyu0u** [comment]
@her0807 @Wishoon 같이 하시죠ㅎㅎ

**Comment by boorownie** [comment]
@her0807 @Wishoon
내일 1시에 논의하기로 했는데 시간되면 같이해요 :)

**Comment by Yboyu0u** [comment]
## 0906 화요일 (브라운과의 회의)
### 회의 안건 
- 테스트를 어떻게 개선해 보면 좋을까?

### 정해진 방식 
1. 다른 크루들이 팀에서 취하고 있는 테스트 전략을 들어본다. 
2. 의견을 수립해서 논의 후, 테스트 개선점을 생각해 본다. 
   - 모든 크루들의 의견을 듣는다. 
   - 다음 주간회의때 다시 논의해 본다.

**Comment by Yboyu0u** [comment]
## 0919 월 브리핑 내용 
[문서화 테스트 개선 분석](https://github.com/woowacourse/prolog/discussions/1035)

**Comment by Yboyu0u** [comment]
## 0926 월 브리핑 내용 

[문서화 테스트 진행상황](https://github.com/woowacourse/prolog/discussions/1041#discussioncomment-3730926)
