### ISSUE TITLE
최신 레벨로그 조회 화면 구현

### ISSUE THREAD

**Issue by seokhongkim** [woowacourse/prolog#1011]

**Comment by wonsss** [comment]
디자인 일관성을 위해 `최신 학습로그` UI 컴포넌트를 재활용하여 `최신 레벨로그` UI를 구현하였습니다.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/59413128/189858692-01cbc2b4-5f40-43af-8110-7ea37bf4c15a.png">
