### ISSUE TITLE
4레벨 세션 추가

### ISSUE THREAD

**Issue by yhh1056** [woowacourse/prolog#1026]
<img width="334" alt="스크린샷 2022-09-10 오후 11 52 16" src="https://user-images.githubusercontent.com/58363663/189488797-5b3514af-48db-469a-9e0b-88025b48538a.png">

4레벨과 관련된 포스팅을 하고싶은데 세션이 존재하지 않습니다.

**Comment by Wishoon** [comment]
다음 주 안에 추가하도록 할게요 👍
