### ISSUE TITLE
프론트 배포 스크립트에 클라우드 프론트 갱신을 추가한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#1075]

**Comment by gracefulBrown** [comment]
## Actions secrets
- AWS_CLOUDFRONT_DISTRIBUTION_DEV
- AWS_CLOUDFRONT_DISTRIBUTION_PROD

**Comment by Yboyu0u** [comment]
# 10월 30일 일요일 시점 작업 상황 
## CloudFront란? 
- AWS에서 제공하는 CDN 서비스
- 캐싱을 통해 사용자에게 좀 더 빠른 전송 속도를 제공함을 목적으로 한다.

### CDN이란?

- Content Delivery Network
- 서버와 사용자 사이의 물리적인 거리를 줄여 콘텐츠 로딩에 소요되는 시간을 최소화한다.
- CDN은 각 지역에 캐시 서버를 분산 배치해, 근접한 사용자의 요청에 원본 서버가 아닌 캐시 서버가 콘텐츠를 전달

ex) 미국에 있는 사용자가 한국에 호스팅된 웹 사이트에 접근하는 경우, 미국에 위치한 Edge server에서 웹사이트 콘텐츠를 사용자에게 전송하는 방식 

### Origin Server

- 원본 데이터를 가지고 있는 서버
- 보통 AWS에서의 Origin Server는 S3, Ec2 instance이다.

### Edge Server (Edge Location)

- AWS에서 실질적으로 제공하는 전 세계에 퍼져있는 서버
- Edge Server에는 요청받은 데이터에 대해서 같은 요청에 대해서 빠르게 응답해주기 위해 Cache 기능을 제공

### Cloud Front 데이터 전송이 발생하는 과정

1. 클라이언트로부터 Edge Server로의 요청이 발생 
2. Edge Server는 요청이 발생한 데이터에 대하여 캐싱 여부 확인 
3. 사용자의 근거리에 위치한 Edge Server 중 캐싱 데이터가 존재한다면 사용자의 요청에 맞는 데이터를 응답 
4. 사용자의 요청에 적합한 데이터가 캐싱되어 있지 않은 경우 Origin Server로 요청이 포워딩됩니다. 

### 그래서 문제가 되는 상황

- 캐시가 없는 엣지는 오리진에 있는 파일을 가져오지만, 이미 캐시가 있는 엣지는 요청을 캐시된 파일을 전달하는 걸로 마무리

→ 요청 처리 속도에서 캐시된 파일을 바로 전달해주니까 유리 

❗️**하지만 캐시된 파일의 TTL(만료 기간)이 아닉 남아 있는데, 오리진 파일이 변경되는 경우**

ex) 사이트의 이미지가 바뀌는 경우 문제가 발생! 

❗️**따라서 클라우드 프론트 개시를 무효화해야 한다!** 

### 해결법

**새롭게 올라간 파일들을 CloudFront를 통해 바로 볼 수 있도록 invalidation 시켜줘야 한다.** 

### 배포 스크립트 수정

**적용 전**

```jsx
name: front deploy for prod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install Dependencies
        run: |
          cd frontend
          yarn
      - name: Build
        run: |
          cd frontend
          yarn build:prd
        env:
          CI: false

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 frontend/build s3://prolog-deploy 
```

**적용 후**

추가된 명령문 

```jsx
- name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION_PROD}} --paths "/*"
```

front dev

```jsx
 env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
					AWS_CLOUDFRONT_DISTRIBUTION_PROD: ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION_PROD}}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 frontend/build s3://prolog-deploy 
			- name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION_DEV}} --paths "/*"
```

front prod 

```jsx
 env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
					AWS_CLOUDFRONT_DISTRIBUTION_PROD: ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION_PROD}}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 frontend/build s3://prolog-deploy 
			- name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION_PROD}} --paths "/*"
```
