### ISSUE TITLE
포스트 작성 > 태그 등록 기능

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#112]
<img width="532" alt="스크린샷 2021-06-16 오후 4 51 22" src="https://user-images.githubusercontent.com/46308949/122184572-51bbad80-cec7-11eb-814a-0ec3ab3439e5.png">

**Comment by sunhpark42** [comment]
프론트엔드 기능 구현 완료되었습니다.

<img width="296" alt="스크린샷 2021-06-17 오후 4 05 05" src="https://user-images.githubusercontent.com/67677561/122348221-e5ec4a00-cf85-11eb-8e78-37b3f3755f89.png">

<img width="582" alt="스크린샷 2021-06-17 오후 4 06 13" src="https://user-images.githubusercontent.com/67677561/122348277-f3a1cf80-cf85-11eb-8361-a80da7015a21.png">

<img width="1113" alt="스크린샷 2021-06-17 오후 4 07 25" src="https://user-images.githubusercontent.com/67677561/122348473-2b107c00-cf86-11eb-9fa0-76091fc00f39.png">

**Comment by gracefulBrown** [comment]
#114 에서 작업 완료되었습니다 :) 고생 많으셨어요~
