### ISSUE TITLE
프롤로그 기능을 정리 한다. - 레벨1

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#1166]
## 작업 대상
- 서비스 기능 작업
  - [x] #1156
  - [x] #1161
  - [x] #1180
  - [x] #1181
  - [x] #1182
  - [x] #1183

- 인프라 작업
  - ES 작업
    - [x] #1186
    - [x] #1189
  - DB 테이블 스키마 정리
    - [x] #1192
    - [x] #1191
  - flyway 작업
    - [x] #1190
    - [x] #1193
    - [x] #1185

- 이외 작업
  - [x] #1194
  - [x] #1195

## 작업 진행 방법
- [x] 돌아가면서 몹 프로그래밍으로 진행한다.
- [ ] #1267 
  - 큐컴버 작성을 함께 하면서 ATDD로 진행한다.

## 참고 링크
- https://github.com/woowacourse/prolog/discussions/1105
- https://github.com/woowacourse/prolog/discussions/1151#discussioncomment-4814935
- #1213

**Comment by kang-hyungu** [comment]
- 미션 기능을 삭제하려다가 남긴 이유
  - 크루들이 많이 쓰고 있음. 좀더 지켜보고 결정하기로 함

**Comment by kang-hyungu** [comment]
프롤로그 기능 정리를 3월 내에 끝내기 어려울 수 있다.
티켓 우선순위를 정해서 진행한다.
- 서비스 기능 작업의 프로필 관련 삭제는 3월 내에 모두 진행한다.
- DB 테이블 스키마 정리와 flyway 작업를 먼저 진행한다.

**Comment by gracefulBrown** [comment]
- 인프라 작업에서 ES 개선 보다는 Flyway와 profile 작업을 우선으로 진행한다.
  - 크루들이 작업할 때 영향을 많이 받는 것을 우선으로 진행
  - 크루들의 눈높이에 맞추기
