### ISSUE TITLE
온보딩을 준비한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#1167]

**Comment by kang-hyungu** [comment]
4/11에 레벨2 시작.

**Comment by kang-hyungu** [comment]
크루 대상 온보딩

# 크루들에게 뭘 시키지?
1. 리뷰어 모집
  - 어떻게 모집할지 구체적인 논의 필요
  - 이전 기수가 맡은 역할은 리뷰어인가 아니면 다른 역할을 더 맡길 수 있는가
    - 이전 기수가 알려주는 레거시 시스템
2. 히스토리
  - 서비스 소개
  - 이전 기수랑 인사 & 소통
    - 이전 기수의 명확한 역할 정하기
      - 굿 퍼스트 이슈를 할당하고 프롤로그 맛보기
        - 리뷰어로 전 기수 지정
        - [이슈 링크](https://github.com/woowacourse/prolog/issues?q=is%3Aissue+label%3A%22good+first+issues%22+is%3Aclosed)
3. ~~레벨3에~~ 개발하려면 필요한 지식들
  - 초기 셋팅
    - 프론트
      - 백엔드 없이 개발할 수 있는 환경
    - 백엔드
      - 어드민
  - 배포 전략
    - 브랜치 전략
  - 모니터링
    - 우선순위를 낮추자. 레벨2에서 크루들이 모르는 상태.
    - 로그 분석
    - 클라우드 와치

**Comment by kang-hyungu** [comment]
프론트 코치가 필요한 영역은 없을까?
프론트 코치 도움이 필요한 부분이 없을지 고민 필요

**Comment by kang-hyungu** [comment]
레벨2에서 할 일들을 정리함
레벨3는 아직 정하지 않음

**Comment by kang-hyungu** [comment]
굿 퍼스트 이슈를 어떤 것으로 할지... 
스프링, 리액트 같은 기술을 갖추지 않아도 처리 가능한 맛보기 이슈를 배정해야 한다.

**Comment by gracefulBrown** [comment]
4월 3일: 백엔드 GFI 이슈 생성 + 온보딩 이슈 생성 방법 정하기
4월 11일: 온보딩 오리엔테이션 + 개선 원하는 부분 찾아오기
4월 17일: 프론트엔드 GFI 이슈 생성
