### ISSUE TITLE
올해 근로 운영 방법에 대해서 논의한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#1169]
## 논의 전 고민해오면 좋을 내용
- 이번 근로에서 해보고 싶은것이 무엇인지

## 논의에서 다룰 내용
- 개발하고 운영할 기능을 결정한다.(아티클 등)
- 크루들과 협업하는 방법에 대해서 이야기한다
- 수료한 크루들과의 협업 방법에 대해서 논의한다.
- #1166 의 기능을 코치별로 나누어 진행한다
  - 티켓을 생성하기

**Comment by gracefulBrown** [comment]
- 학습로그, 학습로그 말하기, 로드맵 등 활동별로 담당을 두어 운영하면 어떨까?

**Comment by kang-hyungu** [comment]
레벨2 시작 전 까지 할 일
기능 정리
누구를 뽑을것인가
온보딩 방법

**Comment by gracefulBrown** [comment]
레벨2: 온보딩 
레벨3: 아티클과 로드맵 두 방향으로 진행
