### ISSUE TITLE
근로 운영 방법에 대해 논의한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#1177]
## 안건

- 고정 근로 업무 시간

**Comment by kang-hyungu** [comment]
크루들 근로에 투입하기 전 주에 고민해보자.
지금 고민하면 까먹음...

**Comment by seokhongkim** [comment]
### 논의한 내용
- 주당 근로 시간을 정할 것인가?
  - 일 1~2시간, 주 최대 10시간 이내로 사용한다. 주말은 제외한다.
    - 근로의 우선 순위가 밀리는 경향이 있어서, 주 단위라도 시간을 정할 필요가 있다.
  - 회의 시간, 페어 시간을 정하는 리소스를 절약하기 위해 아래 시간을 근로에 고정으로 사용한다.
    - **매주 월요일 3시-4시 근로 회의**
    - **매주 수요일, 금요일 4시-6시 근로 페어**
  - 위 시간에는 게더타운에 접속해서 업무를 진행한다.
- 레벨2 초반에 서비스 개발이 어려운 점은 어떻게 하면 좋을까?
  - 업무 파악, 코드 분석, 온보딩 집중 기간으로 활용한다.
  - 서비스 기획 등의 업무도 포함한다.
  - 주간 업무 계획을 세우고 이슈를 등록하도록 한다.
