### ISSUE TITLE
프로필 > 역량 API 제거

### ISSUE THREAD

**Issue by seokhongkim** [woowacourse/prolog#1181]

**Comment by kang-hyungu** [comment]
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/15669435/224213318-c759c682-ab6d-4c91-84ec-06a94affbcf9.png">

학습로그와 역량 관련 테스트 삭제할 때 문제 발생
feature에만 학습로그 인수 테스트 남아있는 부분 있음
점검 필요.

**Comment by kang-hyungu** [comment]
베타 배포는 다 같이 모여서 해봅시다
