### ISSUE TITLE
테스트 / 로컬 환경에서 필요한 기본 데이터 관리 방법을 정리하고 코드를 수정한다. (DataLoaderApplicationListener 참고)

### ISSUE THREAD

**Issue by seokhongkim** [woowacourse/prolog#1195]

**Comment by woowahan-neo** [comment]
DataLoaderApplicationListener는 테스트에서 사용하지 않고 로컬에 테스트 더미 데이터를 추가할 때만 사용한다.
"init-data" -> "local"로 변경 후 특정 조건으로 1번만 실행되는 것만 보장해주면 기존의 데이터를 활용할 수 있다.

**Comment by woowahan-neo** [comment]
1. 더미 데이터를 최신 정보로 업데이트 한다.
2. 초기화 코드를 리팩토링 한다.

**Comment by woowahan-neo** [comment]
초기 데이터 설정이 목적이 아니라 로컬 테스트를 위함이다. 최신 정보를 갱신할 필요는 없다.
초기 데이터 설정과 관련된 이슈는 따로 분리하여 이후 크루들이 작업할 수 있도록 한다.
