### ISSUE TITLE
온보딩을 위한 백엔드 테스트 개선 티켓을 만든다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#1205]

**Comment by gracefulBrown** [comment]
## 할 일 
- 대략적인 흐름 (초안) 만들어 놓고
- 멤버 수가 확정되면 구체적으로 계획을 세워서 이슈를 만들기

# 논의 내용 
## 테스트 종류
- 인수 테스트
- 문서화 테스트
- 통합 테스트
- 단위 테스트

## 작업 예시
- 인수 테스트 성공하는 하나의 인수 테스트만 남기고 나머지는 중복 제거하게 하기
- 통합 테스트 성공하는 하나의 통합 테스트만 남기고 나머지는 중복 제거하게 하기
- 단위 테스트 중에 스프링에 의존하지 않는 대상 테스트 보완
  - 있으면 제거하고 의존하지 않게 수정하기
  - 테스트 더블은 써도 되고 안써도 됨
- 단위 테스트 > 도메인 계층 컨벤션 만들어서 

### 통합 테스트
- Repository를 바라보는 통합테스트를 제외하고 모두 제거하기

## 액션 플랜
- 온보딩용 테스트 가이드 만들기 @seokhong

**Comment by seokhongkim** [comment]
### 백엔드 온보딩 제안
- flyway 리서치 (1개 페어)
- mockito + junit 을 이용한 테스트 작성 방법 정리 (1개 페어)
- 아래 도메인 중 간단한 도메인을 정해서 테스트 작성 (나머지 페어)
  - 총 10개 이상의 테스트를 작성하되, 아래 요건을 준수
    - 최소 1개의 서비스 클래스에 대해 4개 이상의 분기에 대한 테스트 작성 (mockito + junit 을 이용한 테스트 작성 연습)
    - 최소 1개의 도메인 클래스에 대해 4개 이상의 분기에 대한 테스트 작성
- 개선하고 싶거나 개발하고 싶은 아이템 정리 (전체)

### 백엔드 테스트 작성 대상

- 괄호 안의 숫자는 브랜치 커버리지

- [ ] badge
  - application
    - ComplimentKingBadgeCreator (0/2)
    - PassionKingBadgeCreator (0/2)
  - domain
    - FourthCrewSessions (3/6)
- [ ] member
  - application
    - MemberService (0/4)
  - domain
    - Member (7/16)
    - MemberGroup (0/6)
    - MemberTag (0/16) -> `equals()` 구현을 제외하면 5개 정도의 분기가 있는 것으로 예상
- [ ] roadmap
  - application
    - EssayAnswerService (0/2)
    - KeywordService (0/6)
    - NewSessionService (0/2) -> SessionService 에 합치는 것을 고려해야 함.
    - QuizService (0/2)
  - domain
    - EssayAnswer (0/4)
    - Keyword (1/12) -> `equals()` 구현을 제외하면 7개 정도의 분기가 있는 것으로 예상
- [ ] session
  - application
    - MissionService (0/6)
    - SessionMemberService (0/4)
    - SessionService (0/6)
  - domain
    - Mission (1/16) -> `equals()` 구현을 제외하면 2개의 분기가 있는 것으로 예상
    - Session (1/16) -> `equals()` 구현을 제외하면 2개의 분기가 있는 것으로 예상
- [ ] studylog
  - application
    - CommentService (0/4)
    - PopularStudylogService (0/14)
    - StudylogLikeService (0/2)
    - StudylogScrapService (0/2)
    - StudylogService (0/30)
    - TagService (0/2)
  - domain
    - Studylog (1/8)

- [ ] levellogs -> 삭제 대상
  - application
    - LevelLogService (0/8)
  - domain
    - LevelLog (0/40) -> `@EqualsAndHashcode` 영향으로 보이며, 실제 분기는 6개로 예상

**Comment by seokhongkim** [comment]
#1232 로 백엔드 테스트 작성 티켓 생성했습니다.
