### ISSUE TITLE
온보딩 이슈를 생성하고 할당한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#1209]
- [ ] 크루들로부터 개선하고 싶은 내용을 수집하기
- [ ] 수집한 내용 중 적절한 내용을 이슈로 생성
- [ ] 생성한 이슈를 크루들에게 할당

**Comment by seokhongkim** [comment]
### 백엔드 테스트 작성 대상

- 괄호 안의 숫자는 브랜치 커버리지

- [ ] badge
  - application
    - ComplimentKingBadgeCreator (0/2)
    - PassionKingBadgeCreator (0/2)
  - domain
    - FourthCrewSessions (3/6)
- [ ] levellogs -> 삭제 대상
  - application
    - LevelLogService (0/8)
  - domain
    - LevelLog (0/40) -> `@EqualsAndHashcode` 영향으로 보이며, 실제 분기는 6개로 예상
- [ ] member
  - application
    - MemberService (0/4)
  - domain
    - Member (7/16)
    - MemberGroup (0/6)
    - MemberTag (0/16) -> `equals()` 구현을 제외하면 5개 정도의 분기가 있는 것으로 예상
- [ ] roadmap
  - application
    - EssayAnswerService (0/2)
    - KeywordService (0/6)
    - NewSessionService (0/2) -> SessionService 에 합치는 것을 고려해야 함.
    - QuizService (0/2)
  - domain
    - EssayAnswer (0/4)
    - Keyword (1/12) -> `equals()` 구현을 제외하면 7개 정도의 분기가 있는 것으로 예상
- [ ] session
  - application
    - MissionService (0/6)
    - SessionMemberService (0/4)
    - SessionService (0/6)
  - domain
    - Mission (1/16) -> `equals()` 구현을 제외하면 2개의 분기가 있는 것으로 예상
    - Session (1/16) -> `equals()` 구현을 제외하면 2개의 분기가 있는 것으로 예상
- [ ] studylog
  - application
    - CommentService (0/4)
    - PopularStudylogService (0/14)
    - StudylogLikeService (0/2)
    - StudylogScrapService (0/2)
    - StudylogService (0/30)
    - TagService (0/2)
  - domain
    - Studylog (1/8)

**Comment by seokhongkim** [comment]
### 4/17 온보딩 이슈 준비

#### 2주차 크루 업무

- 프론트엔드
  - 지난주와 동일한 페어로 진행한다.
  - 각 페어가 진행하고 싶은 업무 컨펌 받는다.
- 백엔드
  - 새로운 2인 페어로 구성한다.
  - #1232 에 페어별로 작성할 테스트를 나눠놓고, 각 페어가 골라서 진행한다.

#### 프로젝트, 위키 권한

- 팀을 등록하고 크루를 초대한다.
