### ISSUE TITLE
테스트에서 사용하는 테이블 스키마 생성을 하이버네이트에서 flyway로 변경한다.

### ISSUE THREAD

**Issue by woowahan-neo** [woowacourse/prolog#1210]
## 추가 작업
- [ ] 문서화 테스트의 `Documentation` 을 제거하고 `NewDocumentation`만 사용하도록 변경한다.

**Comment by woowahan-neo** [comment]
CI/CD 환경에서 Docker를 활용할 수 있는 방법이나 테스트용 DB 생성하는 방법을 고려한다.

**Comment by seokhongkim** [comment]
### 3/23 확인한 내용
* 테스트중인 브랜치: chore/github-action-mysql-test
  * PR: https://github.com/woowacourse/prolog/pull/1216
* 깃헙 액션에서 서비스 기능을 이용하여 도커 컨테이너 실행이 가능하다.
* flyway + documentation test 까지 정상적으로 실행된다.

#### 참고
* [github action services 문서](https://docs.github.com/ko/actions/using-containerized-services/about-service-containers)
* 블로그 글 - [Github Action으로 자동 test하기!](https://rdd9223.github.io/github%20action/Github_Action/)

**Comment by seokhongkim** [comment]
* 서비스에 대한 통합 테스트를 모두 제거하고, 레포지토리에 대한 통합 테스트만 남김.
* `@RepositoryTest`를 이용한 통합 테스트, 단위 테스트는 모두 성공하는 것 확인 완료.
