### ISSUE TITLE
5기 크루의 멘토로 지원한 크루들과 오리엔테이션을 진행한다.

### ISSUE THREAD

**Issue by seokhongkim** [woowacourse/prolog#1226]
- 오리엔테이션은 4/18 화요일에 진행한다.
  - 슬랙 채널에 초대해서 일정 확인 
- 다음주 월요일에 멘토를 배정하고, 수요일에 페어를 할 때 발생한 이슈에 대해 문의할 수 있도록 가이드한다.

**Comment by gracefulBrown** [comment]
## 오리엔테이션 영상
https://woowahan.zoom.us/rec/share/Cwhz-79cMi7A8GSRExd9oT2bCjzMglPzi9oN1dc-c5Oi3e8S2T3ocsTNojacz_uz.hJORXmIQZHkqSRD0
암호: kdW5Zgc#
## 멘토 활동이란?
5기 크루의 성공적인 프롤로그 프로젝트 적응에 도움을 줍니다.
멘토가 되어 질문이나 코드 설명 등 가이드를 해주어 적응을 돕습니다.
## 멘토 활동은 왜 하나요?
사이드 프로젝트를 진행하며 리더십 역량을 기르는 경험을 할 수 있습니다.
5기 크루들과 소통하며 개발자로서의 소통 역량을 기를 수 있습니다.
## 멘토 활동 방법
멘토와 멘티(5기 크루) 매칭을 한 다음 멘티들이 해당 이슈를 수행하는데 필요한 도움을 줍니다.
## 5기 온보딩 방법
### 백엔드
[테스트 코드 개선의 이슈](https://github.com/woowacourse/prolog/issues/1232)를 할당 받습니다.
### 프론트엔드
간단한 UI 개선 사항을 찾습니다.
찾은 개선 사항 중 해결하고 싶은 내용을 코치들에게 컨펌을 받습니다.
컨펌 받은 내용을 이슈로 등록하여 진행합니다.
## 멘토의 도움이 필요한 부분
프로젝트 초기 설정
이슈 생성 및 개발 진행 시 사전 지식이 필요한 경우 질문 답변
배포 전략 안내
코드 리뷰
## 소통 방법
다음과 같이 안내함
오늘 멘토 오리엔테이션이 진행 될 예정이오니 작업 시작은 내일 멘토와 함께 진행해주세요!
(멘토는 일과 시간에 업무중일 가능성이 있으니 비동기로 소통해주시면 좋을 것 같습니다)
크루들이 채널 혹은 DM을 개설 예정
이슈 해결에 대한 전반적인 내용에 대해 멘토링
먼저 알려줄 필요는 없고 질문에 대한 내용에 대해 안내하는 것을 기본으로 함
이슈 해결 시 문제를 바로 해결해주기 보다는 키워드나 접근 방식 제공을 하면 좋습니다.
