### ISSUE TITLE
포스트 목록 정렬 및 페이징

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#127]

**Comment by sihyung92** [comment]
글 전체목록 요청 시 page와 limit를 query parameter로 요청한다.

AS IS
GET /posts 
```
[ 
  {
    "id" : 1,
    "author" : {
     ...  
    },
  ...
  },
  {
    "id" : 2,
    "author" : {
     ...  
    },
  ...
  },
  ...
]
```

TO BE

GET /posts?page=1&limit=20
(query parameter가 null일 경우 defualt page=1, limit=20)
```
{
  data = [ 
    {
      "id" : 1,
      "author" : {
       ...  
      },
    ...
    },
    {
      "id" : 2,
      "author" : {
       ...  
      },
    ...
    },
    ... // 20개 데이터
  ],
  totalCount = 146, // 총 글 개수
  totalPage = 8 // 총 페이지 수
  currPage = 1, // 현재 페이지
  limit = 20, // 나누는 기준
  order = desc // ASC 오름차순 혹은 DESC 내림차순
}
```

느낌으로 반환 데이터에 페이징에 대한 정보를 추가하는 식으로 기능 구현하려고 하는데 어떤가요?? 의견 부탁드립니당!

**Comment by gracefulBrown** [comment]
### request
- spring data core에서 제공하는 Pageable 객체를 참고하여 네이밍을 정하면 어떨까요?
> - page: 페이징 순서
> - size: 한 페이지에 노출되는 아이템 수
> - sort: 정렬 기준(ex. createdAt)
> - direction: 정렬 방향 (DESC or ASC)

https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Pageable.html

### response 
- 요청 시 알 수 있는 정보는 응답하지 않아도 될 것 같아요!
- currPage -> pageIndex 제안해봅니다

**Comment by sihyung92** [comment]
오오 😃 적용해보겠습니닷

**Comment by sihyung92** [comment]
GET /posts?page=1&size=20&direction=desc
(query parameter가 null일 경우 defualt 값 => page=1, size=20, directon=desc)
```
{
  data = [ 
    {
      "id" : 1,
      "author" : {
       ...  
      },
    ...
    },
    {
      "id" : 2,
      "author" : {
       ...  
      },
    ...
    },
    ... // 20개 데이터
  ],
  totalSize = 146, // 총 글 개수
  totalPage = 8 // 총 페이지 수
  currPage = 1, // 현재 페이지
} 
```
이렇게 진행해보겠습니다!

**Comment by sunhpark42** [comment]
@sihyung92 
<img width="412" alt="스크린샷 2021-07-09 오전 9 14 24" src="https://user-images.githubusercontent.com/67677561/125005200-2d05c080-e096-11eb-96a5-6a9348896203.png">

필터 쿼리와 함께 작동 시 totalSize 가 그대로 나와서, 해당 필터에 맞는 totalSize, totalPage로 변경되어야 할 것 같습니다!

**Comment by sunhpark42** [comment]
<img width="1420" alt="스크린샷 2021-07-09 오전 10 54 35" src="https://user-images.githubusercontent.com/67677561/125011821-21b99180-e0a4-11eb-92eb-78dafdfaf954.png">

**Comment by sunhpark42** [comment]
#165
