### ISSUE TITLE
각 스쿼드에서 진행할 작업에 대해서 사전에 논의한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#1328]
## 필요한 역할
- 로드맵 기획 + 개발
- 아티클 기획 + 개발
- 학습로그 기획 운영
  - 학습로그, 학습로그 말하기, 레벨 인터뷰 등
  - 레벨 인터뷰는 DR팀에서 만든 큰 그림 속에서 효율적으로 학습을 할 수 있게 도움을 주는 기획을 고민하기
- 서스테이닝 프로세스 운영

**Comment by gracefulBrown** [comment]
# 아티클
## 기획
- 우테코 크루들은 우테코 기간동안 여러가지 형태의 학습을 하고 그 결과 학습 결과물이 남는다.
- 자신의 학습 결과물을 다시 보면 회고를 할 수 있고 메타 인지를 기를 수 있다.
- 다른사람이 남긴 학습 결과물을 확인하면 학습 방향성에 대해 검토해볼 수 있다.
- 목표: 우테코 크루들의 학습 결과물을 모아볼 수 있는 기능을 제공한다.

## 기대효과
- 우테코에서 생산된 다양한 컨텐츠를 구독하고 관리할 수 있다.
- 일반(외부) 사용자들과 함께 할 수 있는 서비스 / 학습 컨텐츠 커뮤니티

## 예시
- [서핏](https://www.surfit.io/)
- [Disquiet](https://disquiet.io/)
- [Velog](https://velog.io/)

## 핵심 기능
- 자신의 컨텐츠를 링크 형식으로 등록하고 관리할 수 있다.
- 다른사람의 아티클을 볼 수 있다.
- 아티클을 주제별로 종류별로 모아볼 수 있고 검색할 수 있다.

**Comment by seokhongkim** [comment]
# 로드맵

## 기획
- 크루는 우테코에서 여러 미션을 수행하며 학습을 진행하지만, 각 미션에서 학습해야 하는 내용이나 용어를 모를 때가 있다.
- 스스로 학습이 잘 됐는지 확인하는 좋은 방법은 다른 사람에게 설명하는 것이다.
- 적절한 키워드와 질문이 제공된다면 관련 내용을 스스로 찾아서 학습하고 설명할 수 있을 것이다.
- 목표: 우테코 크루들이 스스로 학습할 수 있도록 가이드와 질문을 제공한다.

## 기대효과
- 우테코에서 레벨별로 학습해야 하는 내용을 알 수 있다.
- 학습해야 하는 내용을 깊이 있게 학습했는지 질문에 대해 답변을 작성하며 스스로 알 수 있다.

## 예시
- [우테코 백엔드 로드맵](https://github.com/woowacourse/back-end-roadmap)
- [백엔드 개발자 로드맵](https://roadmap.sh/backend)
- [프론트엔드 개발자 로드맵](https://roadmap.sh/frontend)
- [제로베이스 백엔드 로드맵](https://zero-base.co.kr/event/media_BE_school_roadmap)

## 핵심 기능
- 학습해야 할 키워드를 볼 수 있다.
- 키워드와 관련된 질문을 보고 이에 대해 글을 작성할 수 있다.
- 키워드에 대해 얼마나 학습했는지 알 수 있다.

**Comment by woowahan-neo** [comment]
# 고도화 (작성 중)

## 기획
- 기존 시스템 중 문제가 있거나 개선할 부분을 고도화한다.
- 목표: 학습 고도화라는 본질에 집중하여 시스템적으로 학습에 방해될 수 있는 요소를 제거하고 개선한다.

## 기대효과
- 기존 시스템 중 문제가 있는 부분이 해결된다.
- 기존 시스템을 더욱 좋은 형태로 제공 받는다.

## 예시
- #1231
