### ISSUE TITLE
서비스 이름을 공모한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#14]
- [x] 이름을 공모한다.
- [x] 후보를 추출한다.
- [x] 투표를 하고 결정한다.

**Comment by gracefulBrown** [comment]
검프(김태정)  11 hours ago
학습로꼬
:+1:
3
:-1:
8
:kk:
2


검프(김태정)  11 hours ago
학습그레이
:+1:
4
:-1:
6
:heart:
2


수리(이다원)  11 hours ago
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

파피(김태완)  11 hours ago
ㅁㅔ타몽
:interrobang:
2
:pray:
2


검프(김태정)  11 hours ago
서비스명: 브라운의 식사쿠폰
:-1:
7
:+1:
3
:flushed:
2


파노(전환오)  11 hours ago
아 메타몽 놓쳤다
:sunglasses:
6


서니(박선희)  11 hours ago
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ블러뭐에욬ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

웨지(성시형)  10 hours ago
야유당하는 검프

나봄(윤보민)  10 hours ago
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 겁나웃기넼ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

포모(박은소리)  10 hours ago
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

검프(김태정)  10 hours ago
(학)습로그 (edited) 
:-1:
7
:+1:
2
:male_fairy:
3


코기(김진환)  10 hours ago
기록기록
:갈대코기:
6


코기(김진환)  10 hours ago
끼룩끼룩
:수리:
4


파노(전환오)  10 hours ago
학기습록

나봄(윤보민)  10 hours ago
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

나봄(윤보민)  10 hours ago
야 너두 학습로그?
:+1:
6
:잘가요:
5
:조기수료:
5
:나봄:
5


코기(김진환)  10 hours ago
학습로그 안쓰니
:dengdeng:
5
:dancing_ryan:
5
:갈대코기:
5


검프(김태정)  10 hours ago
이만 머지 하겠습로그:pray::skin-tone-3:
:pray:
9
:이만머지:
9
:조기수료:
8
:잘가요:
8


나봄(윤보민)  10 hours ago
HAK-SEUP LOG

브라운(류성현)  10 hours ago
아니 머야ㅋㅋㅋㅋ 이 스레드 검프한테 털렸네욬ㅋㅋㅋ

코기(김진환)  10 hours ago
검프가 털렸다고 생각합니다!
:neb:
4
:heart:
2
:검프:
2
:beer:
2


손너잘(손민성)  10 hours ago
Log4L (log for learning)
:dongong:
7
:+1:
7


나봄(윤보민)  10 hours ago
검프 :-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1:
:smiling_face_with_tear:
6
:잘가요:
5
:male_fairy:
4
:female_fairy:
4
:fairy:
4
:이만머지:
6


지그(송지은)  10 hours ago
콘솔로그 (edited) 
:+1:
12
:thumbsup2:
11
:blob-100:
8
:-1:
2


지그(송지은)  10 hours ago
로그아웃
:-1:
6


지그(송지은)  10 hours ago
베릴로그
:-1:
5


엘라(김현주)  10 hours ago
ㅋㅋㅋㅋㅋㅋ콘솔로긐ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

지그(송지은)  10 hours ago
창천향로그
:-1:
5


지그(송지은)  10 hours ago
K-학습로그
:-1:
6
:+1:
6
:rolling_on_the_floor_laughing:
1


유조(조윤호)  10 hours ago
로그라타타
:+1:
2


유조(조윤호)  10 hours ago
우테코 학습록
:+1:
2


곤이(김기융)  10 hours ago
호롤로그
:gun:
1
:+1:
1


지그(송지은)  10 hours ago
미안하다 이거 보여주려고 어그로그
:-1:
3
:brain:
7
:+1:
9


나봄(윤보민)  10 hours ago
어그로긐ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
:+1:
2


유조(조윤호)  10 hours ago
라그나로그
:brain:
2


지그(송지은)  10 hours ago
엄마 난 커서 랄로그
:face_vomiting:
4


유조(조윤호)  10 hours ago
양변에 로그를 취한다
:nerd_face:
3
:brain:
3
:gun:
2
:face_vomiting:
2
:bomb:
2


유조(조윤호)  10 hours ago
LGTM(Logs Good To Me)
:멈춰:
1
:+1:
6
:zzang:
1


지그(송지은)  10 hours ago
벌써 어느새 또 밤이되었습로그
:멈춰:
3
:-1:
4


와일더(강규한):냥냥어택_와일더:  10 hours ago
Log of new-wisdom

중간곰(양승현)  9 hours ago
LogBack

웨지(성시형)  9 hours ago
양변에 로그를 취한다

유조(조윤호)  9 hours ago
뽀로로그
:+1:
3


유조(조윤호)  9 hours ago
켈로그
:+1:
4


나봄(윤보민)  9 hours ago
좋은 것만 드려요~

손너잘(손민성)  9 hours ago
좋은것만드려요

손너잘(손민성)  9 hours ago
아 나봄 찌찌뽕

나봄(윤보민)  9 hours ago
ㅋㅋㅋㅋ 내가 빨랐닼ㅋㅋ

유조(조윤호)  9 hours ago
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

지그(송지은)  9 hours ago
제거투표좀

유조(조윤호)  9 hours ago
다앎로그(dialog) (edited) 
:+1:
3


중간곰(양승현)  9 hours ago
vi log

유조(조윤호)  9 hours ago
기억보단 기로그
:+1:
21
:-1:
2
:gun:
2
:party-dinosaur:
1
:meow_party:
1
:party_parrot2:
1


루트(김준근):thinking_face:  9 hours ago
멀(리 가기전에 기)록

수리(이다원)  9 hours ago
아옳옳옳?

체프(심문성)  9 hours ago
멀록 이모티콘이 없군요

크리스(이송원)  8 hours ago
기로그 좋네요

다니(이다은)  8 hours ago
LGTM 넘 좋은데유

다니(이다은)  8 hours ago
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

조이(김주원)  6 hours ago
기억보단 기로그 좋네유:laughing:

**Comment by sunhpark42** [comment]
### 결정
Pro-log(프로그), 대표 아이콘 개구리
