### ISSUE TITLE
유저네임(username) 정책을 정하고 적용한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#141]
### AS IS
- 최초로그인 시 Github profile정보의 login_name에서 받아오는 githubUserName 값이 있음

### 필요한 이름 정보
1. 화면에 노출되는 고유한 이름
2. 화면에 노출되는 중복 가능한 이름

### 계획
- 기존 nickname을 중복 가능한 이름으로 하고 name으로 변경한다.
- 기존 githubUserName을 고유한 이름으로 두고 username으로 변경한다.

### 운영 정책
- name과 username은 github에서 name과 login 값으로 받아온다.
- name은 중복과 빈칸(null or "")이 허용된다.
- username은 중복이 허용되지 않으므로 기존에 같은 username이 있는 경우 뒤에 문자 추가 (ex. `gracefulBrown-a`)
- username은 github의 username 정책을 따른다
> Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen.

### 노출 정책
- 기본적으로 화면에는 {name}({username})으로 노출한다. 
  - ex) 류성현(gracefulBrown)
- name이 없는 경우에는 username만 노출한다.
  - ex) gracefulBrown

### 작업 계획
- 마이페이지에서 name과 username을 변경할 수 있다. (추후 작업 예정)
- 변경 기능 구현 전 까지는 변경이 불가능하다.

**Comment by gracefulBrown** [comment]
## 기존 서비스 사례

### github
- name
- username
![image](https://user-images.githubusercontent.com/46308949/123497266-781bde80-d667-11eb-87fb-73cd11140528.png)
![image](https://user-images.githubusercontent.com/46308949/123497272-81a54680-d667-11eb-97c6-6b6585361712.png)

### instargram
- name
- username
![image](https://user-images.githubusercontent.com/46308949/123496892-6802ff80-d665-11eb-83c8-93a9f5d6138d.png)

**Comment by sunhpark42** [comment]
*   변경 가능한 이름 : nickname, 고유한 이름 : username
*   nickname만 보여주고, default = Username으로 한다.
