### ISSUE TITLE
FlyWay 동작 상태를 enabled로 변경한다

### ISSUE THREAD

**Issue by nuyh99** [woowacourse/prolog#1419]
## 문제 인식
1. 기능 개발 중 DB Schema 변경을 위해 새로운 버전의 flyway 마이그레이션 파일을 추가함
2. 배포를 했지만 flyway가 동작하지 않음

## 원인
- `application.yml` 파일에서 `spring.flyway.enabled = false` 설정으로 돼있음
- Github Actions에서 빌드할 때는 아래와 같이 그래들로 flyway를 동작시켜서 동작하지만 prod, dev에 배포됐을 때는 flyway가 동작하지 않음
<img width="706" alt="image" src="https://github.com/woowacourse/prolog/assets/93072571/9f1a60c8-90b4-44d6-9da8-ab4823364a8e">

## 기타
- 개발 서버 mysql에 접속해서 `flyway_schema_histroy` 테이블을 확인해보니 프로젝트에서 사용되지 않는 V2 파일 이력 확인(성공 여부는 실패 상태)
- 해당 이력 삭제 후 application-dev.yml에서만 임시적으로 `spring.flyway.enabled = true`로 변경하니 정상 동작

**Comment by amaran-th** [comment]
데이터베이스 스키마를 코드로 관리하는 것은 좋지만, 적용하는 것까지 자동화를 하면 위험하기 때문에,
데이터베이스 스키마 변경이 필요한 경우 서버에 직접 접속해서 gradle 명령어로 실행해야 합니다.

그런 관계로 설정을 enabled=false로 유지하기로 하였습니다.
