### ISSUE TITLE
[긴급] 글쓰기 기능이 동작하지 않는 오류를 수정한다

### ISSUE THREAD

**Issue by solo5star** [woowacourse/prolog#1451]
![image](https://github.com/woowacourse/prolog/assets/20203944/4c96d63e-d139-4198-90c9-9086f45b0e90)

글쓰기 기능이 동작하지 않는 오류를 수정해야 한다.

에러 원인:
* 프론트엔드 측에서 /studylogs/temp API를 호출할 때 Authorization 헤더를 넣어주지 않아 발생한 오류이다.
* https://github.com/woowacourse/prolog/blob/main/frontend/src/apis/studylogs.ts#L110 이 라인에 accessToken을 넣어 요청하도록 수정한다.

**Comment by Creative-Lee** [comment]
고생했습니다!
