### ISSUE TITLE
JPA를 적용한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#149]
- [ ] 엔티티 설계
- [x] 테스트 작성

**Comment by sihyung92** [comment]
# 목표

주제 - DAO (JdbcTemplate) => JPA로 변경
일정 - 8월23일(월) 까지
타겟 -
- [ ] 모든 테스트 성공
- [ ] 쿼리 카운트를 DAO 방식과 비교해 지나치게 많아지지 않도록 리팩토링

# 도메인 설계
범례 : **엔티티명**(포함해야하는 엔티티 명, 비어있을 경우 없음)

1. **멤버**() 
2. **포스트** (미션) 
3. **미션** ( )
4. **포스트태그** (포스트, 태그)
5. **태그** ( )

# 변경대상 (DAO 메소드)
## 멤버DAO
### 단건 조회
- [ ] userId
- [ ] githubId
- [ ] userName
### 입력
- [ ] member
### 수정
- [ ] member

## 포스트DAO

### 집계 
- [ ] Pagable을 위한 count 쿼리들 삭제 예정
### 조회 
- [ ] 전체조회 
- [ ] memberID 단건조회
- [ ] userName 단건조회
- [ ] userID 단건조회
- [ ] 미션 및 태그 필터 걸린 단건조회 
### 입력
- [ ] 단건 입력
- [ ] 다수건 입력
### 수정 
- [ ] post
### 삭제
- [ ] post

## 포스트태그

### 단건 조회 
- [ ] postID
### 입력 
- [ ] postId
- [ ] tagId
### 삭제 
- [ ] postId, tagId 삭제
- [ ] postId 일괄삭제

## 태그
### 입력
- [ ] tag
### 조회
- [ ] 단건 조회
- [ ] 전체 조회
