### ISSUE TITLE
다른 사람 프로필 접근 시 해당 사람의 프로필을 노출한다

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#155]

**Comment by HyuuunjuKim** [comment]
- api 명세가 제대로 안뜨는 부분이 있습니다 ㅜ ㅜ( 포스트 목록조회(페이징), 포스트 목록 조회(작성자별), 포스트 단건 조회, 포스트 삭제)
![image](https://user-images.githubusercontent.com/43339385/125253344-462b9d00-e334-11eb-90f4-d334b9ee8272.png)

- 마이페이지가 프로필페이지로 바뀌면서 header에서 authorization이 빠져야 할 부분이 정리가 안된것 같습니다. 지금까지 제가 확인한 바로는
     - 멤버별 포스트 조회에는 지금 authorization이 들어가야 api가 동작하는 것 같은데, 이 부분이 authorization이 없어도 동작하도록 수정되어야할 것 같습니다 ~ ! 이 부분 조금 확인 부탁드립니다 ㅎㅎ
    - 멤버 정보 요청에서 문서에는 authorization이 들어가 있는데 없어도 api가 잘 동작합니다( 문서 정리만 해주시면 될 것 같습니다 🙂 )
     
![image](https://user-images.githubusercontent.com/43339385/125253656-9c004500-e334-11eb-93ab-2c209c220b8f.png)
