### ISSUE TITLE
기존 학습로그 데이터 마이그레이션을 한다

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#159]
- [ ] 회원 정보를 등록해놓는다
- [ ] 기존 학습로그 데이터를 가져와서 저장한다

**Comment by gracefulBrown** [comment]
## 학습로그 조회 스크립트
https://codepen.io/gracefulbrown/pen/MWJypLa?editors=1111

**Comment by gracefulBrown** [comment]
api - 깃허브에서 학습로그 정보를 받아올 수 있는 api

# 멤버
api에서 GitHub id와 username을 받아올 수 있음
이 데이터를 이용해 멤버 insert (nickname은 없는 상태)
추가적으로 GitHub 소셜 로그인 시 멤버가 있을 경우 정보를 업데이트 하는 로직 추가 (논의 필요)
GithubLoginService.createToken() 내부 수정
위 데이터를 파싱해서 Post로 만들어 DB에 insert
RestTemplate 활용 + Object Mapper를 활용해 데이터 파싱
확인해야 될 점 - 전해주는 데이터가 유효한 데이터인지 실제 데이터와 비교(깃허브가서 인간지능 활용)
Post의 content부분을 어떻게 저장하는지, 프론트엔드에서 어떻게 표현되는지 비교 

# 해야할 일
api에 대한 분석 (https://api.github.com/repos/woowacourse/java-lotto/issues/comments?state=all&direction=desc&sort=created_at&per_page=1000&page=${1}&since=2021-02-01T00:00:00Z)
 2. 해당 데이터 파싱 (해당 데이터가 실제 데이터와 일치하는지 비교)
 3. 파싱한 데이터 저장
 4. 저장된 데이터 화면상의 표현 확인하기

**Comment by soulgchoi** [comment]
- [x] api에 대한 분석 (https://api.github.com/repos/woowacourse/java-lotto/issues/comments?state=all&direction=desc&sort=created_at&per_page=1000&page=${1}&since=2021-02-01T00:00:00Z)
- [x] 해당 데이터 파싱 (해당 데이터가 실제 데이터와 일치하는지 비교)
- [x] 파싱한 데이터 저장
- [ ] 저장된 데이터 화면상의 표현 확인하기

**Comment by sihyung92** [comment]
데이터 csv 파일 만들어 논 거 insert 쿼리문으로 변환하는 작업 진행할 예정입니다!

**Comment by soulgchoi** [comment]
[post2.txt](https://github.com/woowacourse/prolog/files/6860288/post2.txt)
[member.txt](https://github.com/woowacourse/prolog/files/6860290/member.txt)
