### ISSUE TITLE
UI / UX에 대해 논의를 한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#16]

**Comment by sunhpark42** [comment]
# 5/12일 회의

## 논의 내용
- 로그인, 전체보기 관련 UI 제작

### 로그인
- 헤더 이용
- 별도 페이지 x
- 로그인 x : 검색버튼 + 로그인 버튼 
- 로그인 o : 검색버튼 + 개인 프로필
  - 개인프로필 클릭 시 마이페이지, 로그아웃 플로팅 가능
#### [와이어 프레임]
<img width="955" alt="login" src="https://user-images.githubusercontent.com/67677561/117903225-1c410480-b30a-11eb-89e1-b1f95fc1d06d.png">

### 전체보기
- 필터 기능
- 저자, 제목, 태그 보여주기
- 썸네일의 경우 학습로그 작성 피로도를 증가시킬 수 있을 것 같아 제외함.
#### [와이어 프레임]
<img width="753" alt="스크린샷 2021-05-12 오전 10 10 06" src="https://user-images.githubusercontent.com/67677561/117903320-4a264900-b30a-11eb-8313-2d6b6214f659.png">

**Comment by gracefulBrown** [comment]
@sunhpark42 좋아요! 어떤 버튼인지 더 잘 알 수 있을 것 같아요 👍

**Comment by gracefulBrown** [comment]
## UI 및 디자인
https://xd.adobe.com/view/fac630d8-51dc-4c6d-b479-947663a4b886-af95/

**Comment by gracefulBrown** [comment]
@sunhpark42 
추가로 논의할 사항이 없으면 논의 결과를 wiki에 이동 시켜 주신 후 해당 이슈를 close 해주세요~

**Comment by sunhpark42** [comment]
@gracefulBrown 마일스톤 기준으로 close 하면 될까요?

**Comment by sunhpark42** [comment]
학습로그 로그인, 글 작성, 전체보기, 개별보기 UI 논의 완료
