### ISSUE TITLE
새로 생성된 태그로 필터링이 안되는 이슈

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse/prolog#165]
<img width="178" alt="스크린샷 2021-07-12 오전 9 01 20" src="https://user-images.githubusercontent.com/67677561/125214027-d4c9fb00-e2ef-11eb-9eb6-e421d2dfed19.png">

<img width="1120" alt="스크린샷 2021-07-12 오전 9 01 30" src="https://user-images.githubusercontent.com/67677561/125214023-d0054700-e2ef-11eb-8b3b-b95902d796a6.png">

새 글 작성후, 생성된 태그로 검색이 안됩니다.

**Comment by sunhpark42** [comment]
필터링의 경우 생성된 글이 있는 페이지에서 필터링을 할 경우 필터가 잘 되나, 이 외의 페이지에서 필터링 시 에러가 있는 것을 확인하였습니다.
### 요청 (생성된 글이 있던 페이지의 경우)
![스크린샷 2021-07-13 오후 9 11 39](https://user-images.githubusercontent.com/67677561/125449402-5db1bf67-c744-45ff-9457-5874c3af2617.png)
### 응답
```
{"data":[{"id":16,"author":{"id":2,"username":"sunhpark42","nickname":"sunhpark42","role":"CREW","imageUrl":"https://avatars.githubusercontent.com/u/67677561?v=4"},"createdAt":"2021-07-13T21:03:04.963972","updatedAt":"2021-07-13T21:03:04.963972","mission":{"id":1,"name":"3기-프론트엔드-레벨1-자동차경주"},"title":"123","content":"123","tags":[{"id":5,"name":"1234"}]},{"id":15,"author":{"id":2,"username":"sunhpark42","nickname":"sunhpark42","role":"CREW","imageUrl":"https://avatars.githubusercontent.com/u/67677561?v=4"},"createdAt":"2021-07-13T21:01:44.201723","updatedAt":"2021-07-13T21:01:44.201723","mission":{"id":1,"name":"3기-프론트엔드-레벨1-자동차경주"},"title":"adfa","content":"aadfsa","tags":[{"id":5,"name":"1234"}]}],"totalSize":2,"totalPage":1,"currPage":2}
```

### 요청 (생성된 글이 없는 페이지의 경우)
![스크린샷 2021-07-13 오후 9 12 55](https://user-images.githubusercontent.com/67677561/125449580-8393a8ec-d570-4a83-867e-8738e8820776.png)
```
{"data":[],"totalSize":2,"totalPage":1,"currPage":1}
```

**Comment by gracefulBrown** [comment]
## 원인 
- where 조건이 적용되기 전에 limit이 걸려서 조회가 안됨

## 상황 재현
- 포스트가 10개가 있는 상황에서 새로운 태그와 함께 새로운 글 추가
- 새로운 태그로 필터 설정하여 조회 할 경우 기존 포스트 10개 중 새로운 태그를 가진 포스트를 찾기 때문에 결과를 찾을 수 없었음

## 해결
- limit 조건을 where 절 이후로 이동

## 작업
https://github.com/woowacourse/prolog/commit/25fa6bca70914b6b13891f3ad0ac4faaa542e9d6
