### ISSUE TITLE
문서화 테스트를 stub으로 대체한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#166]

**Comment by qhals321** [comment]
현재 문서화 테스트와 인수 테스트가 분리가 되어있어서 리팩토링 하거나 기능을 완성할 때 주의를 기울여야할 부분이 많다고 느꼈습니다!
또한, 의미있는 문서화를 위해 문서화 테스트에 의미있는 사전 데이터 세팅도 필요해서 한 번 더 테스트를 하는 기분이 들었습니다!

인수 테스트와 문서화 테스트를 합치면 어떨까라는 의견입니다!

두 가지 방법을 생각해보았습니다~!
### 첫 번째 방법 : 시나리오에 직접 테스트 문서화를 기입하기
```
  Scenario: 해당 유저의 포스트 목록 월별로 조회하기
    Given "브라운"이 로그인을 하고
    When "브라운"의 2020년 5월 포스트 목록을 조회하면
    And "members/login"로 문서화되고
    Then 해당 유저의 포스트 목록이 조회된다
```
위와 같이 작성하면 저절로 문서화하는 코드가 동작되게끔 하면 어떨까 생각했습니다!
하지만 시나리오에 뜬금없는 문서화가 존재하는 것 같아 이 방법은 시나리오 가독성 면에서 좋지 않은 것 같네요..!

### 두 번째 방법 : Then 코드에 직접 테스트 문서화 코드 기입하기
이 방법은 직접 `StepsDefinition`에 `Then` 에 개발자가 직접 테스트 문서화를 할 수 있는 메서드를 제공하면 좋겠다고 생각했습니다!
예를 들어 아래와 같은 느낌으로요!
```
    @Then("해당 유저의 포스트 목록이 조회된다")
    public void 나의포스트목록이조회된다() {
        Response response = request().withDocument("members/calendar-post").getResult();
    }
```

위와 같이 인수 테스트와 문서화 테스트를 합치게 된다면 `RestAssured` 를 사용하다 보니 많은 코드 변화가 일어날 것 같네요!
예를 들어 `RestAssured` 를 이용해 문서화를 하고 싶다면 `given("문서화주소")` 메서드를 이용해야 하는데 실제로 인수 테스트에서 문서화를 해야 되는 시점은 `Then` 시점이라 `RestAssured` 요청 자체를 lazy하게 요청해야할 것 같네요! (`getResult()` 를 하는 순간 모든 요청 응답 처리를 하는 방식처럼요!)

저의 의견을 조심스럽게... 내봅니다!!!

**Comment by gracefulBrown** [comment]
정말 좋은 아이디어네요!
하지만 인수 테스트 수행 사이클과 문서화 테스트의 수행 사이클이 다를 수 있고 독립적으로 수행되어야할 것 같아서 따로 가져가는게 좋을 것 같아요ㅠㅠ

**Comment by gracefulBrown** [comment]
[#755](https://github.com/woowacourse/prolog/issues/755)에서 이어서 진행합니다.
