### ISSUE TITLE
로그인 만료된 상태로 접속 시 마이 페이지 오류

### ISSUE THREAD

**Issue by soulgchoi** [woowacourse/prolog#179]
![image](https://user-images.githubusercontent.com/52682603/126599191-5cfba3d5-272e-4910-9afa-2907eba9d199.png)

로그인 만료된 상태로 마이페이지에 접속 시 프로필 이미지가 깨집니다!
어떤 유저의 페이지인지 없어서 생기는 문제인 것 같습니다.
저는 프로그 페이지 url 을 직접 입력해서 접속하는 경우가 많은데, 항상 이런 화면이 먼저 뜹니다.

**Comment by gracefulBrown** [comment]
현재는 해결된 이슈입니다. 다시 발생하면 reopen 하겠습니다.
