### ISSUE TITLE
태그 개수 만큼 글이 조회되는 오류

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse/prolog#191]
오류 상황
1. 글 작성
2. 태그에 2개 이상의 태그 추가
3. 태그 개수만큼의 글이 작성되어있음.

![스크린샷 2021-07-27 오전 11 32 40](https://user-images.githubusercontent.com/67677561/127086470-e7bce911-c03c-458a-bb74-df3e0c32eb12.png)

**Comment by sihyung92** [comment]
^^ 이런 치명적인 버그가!! 확인하겠습니다!!
제보 감사합니다 !! ^^
^_______^

**Comment by sunhpark42** [comment]
글 작성이 문제인 줄 알았는데, 하나를 삭제하니 두개가 모두 삭제되네요. 조회 문제인 것 같습니다.
