### ISSUE TITLE
본문 작성 중 카테고리 선택 불가능

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse/prolog#209]
### 아직 본문이 작성되지 않은 경우
![image](https://user-images.githubusercontent.com/37354145/127938149-ee90ca0a-a72d-4fb6-a30b-1139f686a115.png)

<br>

### 본문이 작성된 경우
![image](https://user-images.githubusercontent.com/37354145/127938195-1ed1f2bb-bc7e-496b-9dbb-98e075f14bba.png)
![image](https://user-images.githubusercontent.com/37354145/127938239-4b6e8f35-d79a-4a9e-8d22-5ff8572686b4.png)

<br>

카테고리보다 본문 내용이 우선적으로 선택되어 해당 영역의 카테고리는 선택이 불가능합니다.

**Comment by gracefulBrown** [comment]
#226 이슈와 중복 이슈 닫겠습니다~
