### ISSUE TITLE
링크 그대로를 입력하면 hyperlink가 생기지 않는다.

### ISSUE THREAD

**Issue by dudtjr913** [woowacourse/prolog#213]
![image](https://user-images.githubusercontent.com/64782636/128036400-88f38bd6-f213-4be7-920d-0827d7583b61.png)
위와 같이 제목을 입력하지 않으면 링크가 생성되지 않습니다.

아래와 같이 제목을 입력하면 정상적으로 링크가 생성됩니다.
![image](https://user-images.githubusercontent.com/64782636/128036620-d95ea0d5-4ad9-4455-b6a3-10fda298103a.png)

**Comment by gracefulBrown** [comment]
#227 이슈에서 진행하겠습니다.
