### ISSUE TITLE
마이페이지의 글 개수가 고정되어 있다.

### ISSUE THREAD

**Issue by dudtjr913** [woowacourse/prolog#214]
![image](https://user-images.githubusercontent.com/64782636/128039011-40d513e6-a076-4d13-8400-48ba71bc6f61.png)
마이페이지의 글 개수가 고정되어 있어서 글을 작성하면 이전 글을 볼 수 없습니다

**Comment by gracefulBrown** [comment]
#207 이슈와 중복입니다.

**Comment by dudtjr913** [comment]
넵!! 이슈 닫겠습니다~

**Comment by dudtjr913** [comment]
넵!! 이슈 닫겠습니다!
