### ISSUE TITLE
태그에 -가 2번 이상 들어가면 오류가 발생한다.

### ISSUE THREAD

**Issue by dudtjr913** [woowacourse/prolog#215]
태그에 -가 한개일 땐 정상적으로 작성이 되는데 2개 이상일 경우에는 에러가 발생합니다.
![image](https://user-images.githubusercontent.com/64782636/128041366-adb8f2a1-abb2-42ef-bd33-956defacb204.png)

**Comment by bperhaps** [comment]
-가 2번 이상들어가면 발생하는 문제가 아니라, 태그의 길이가 문제입니다.
데이터베이스의 무결성 제약조건이 20자로 되어 있기에 에러가 발생합니다.
프론트엔드에서의 적절한 유효성 검사가 필요해 보이며 백엔드에서도 비즈니스 로직상에서의 유효성 검사가 필요해 보입니다.
