### ISSUE TITLE
프로젝트를 로컬에서 실행시켜 본다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#225]
- [x] 나봄
- [x] 디토
- [x] 서니
- [x] 손너잘
- [x] 엘라
- [x] 웨지
- [x] 조앤
- [x] 티케
- [x] 현구막

**Comment by Hyeon9mak** [comment]
![image](https://user-images.githubusercontent.com/37354145/129463945-a277342e-b587-4ac1-9245-07831d27c062.png)

로컬에서 수행해보니 위와 같이 테스트가 깨지는데요, 혹시 JDK 버전 문제일까요?
