### ISSUE TITLE
태그의 길이 유효성 검사를 진행한다.

### ISSUE THREAD

**Issue by bperhaps** [woowacourse/prolog#236]
database의 태그길이가 varcher(20)으로 고정되있음에도 불구하고 프론트엔드, 백엔드에서의 적절한 유효성 검사를 하지 않습니다.

related with #215

**Comment by sihyung92** [comment]
JPA 팀에서 병합 진행하겠습니다

**Comment by gracefulBrown** [comment]
버그 픽스라서 이것만 따로 진행해주시는게 좋을것 같아요~ @bperhaps
