### ISSUE TITLE
프로필 페이지에서 내가 작성한 글이 보이지 않는 이슈

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse/prolog#242]
작성한 글이 있는데, 프로필 페이지에서 확인이 안됩니다.  
네트워크탭을 확인 했을 때 요청은 정상적으로 보내고, 응답을 받는데,  필터링 된 결과물로 빈 배열이 날아옵니다 ㅠㅠ (totalSize 가 4인데 배열은 빈배열입니다)  
베타페이지를 확인 한 바로는 조회 당일 작성된 포스트만, 프로필 페이지에서 확인이 가능하고, 조회일 이전 포스트는 보이지 않습니다.  
확인부탁드립니다.

![](https://user-images.githubusercontent.com/67677561/129891011-9100f8bf-3113-4aaa-93d6-26581fa575fc.png)

![](https://user-images.githubusercontent.com/67677561/129891092-2e102e07-bc9c-4611-88cb-6108f29dd56c.png)

**Comment by gracefulBrown** [comment]
놓친 부분이 있었네요ㅎㅎ 제보 고마워여~
https://github.com/woowacourse/prolog/commit/b30a8969f4209b661f44b16b044b0ae66ef6a880
