### ISSUE TITLE
글쓰다가 딴짓하고 오면 로그인이 풀려서 글이 날아가는 이슈

### ISSUE THREAD

**Issue by Gomding** [woowacourse/prolog#253]
체감상 30분~1시간 정도 지나면 로그인이 풀려서 글이 사라지는 마술 흑흑..

예전에 우테코 사이트에서 로그인이 풀리던 문제와 비슷한 느낌이에요!

좀 더 자세한 상황을 알게되면 추가하겠습니다!!!

**Comment by bperhaps** [comment]
세션 만료시간에 따른 이슈인것 같은데 버그는 아니고 정책상 문제 같아요.

**Comment by Gomding** [comment]
토큰만료가 딱 1시간 이었네요
딴짓을 1시간이나 해서 죄송..

**Comment by Hyeon9mak** [comment]
어떤 걸 쓰시길레 1시간을...
