### ISSUE TITLE
글 작성중 미션선택창과 에디터창이 겹쳐보이는 문제

### ISSUE THREAD

**Issue by xrabcde** [woowacourse/prolog#254]
![image](https://user-images.githubusercontent.com/56033755/130054133-06843899-5020-4615-8b98-cdfc81a713fa.png)

글 작성중에 미션을 바꾸려고 저 드랍다운?? 메뉴 누르면 저렇게 겹쳐보여요ㅜㅠ
겹치는 부분에 있는 미션들은 선택도 안 되고 있는 것 같습니다...... 😱

**Comment by yujo11** [comment]
<img width="1468" alt="스크린샷 2021-08-20 오후 1 30 35" src="https://user-images.githubusercontent.com/61097373/130179330-a06ef0fa-441a-4314-8090-fc38f342d555.png">

z-index로 우선순위위를 조절해주면 해결 되는거 같습니다람쥐~~
