### ISSUE TITLE
글 작성시간이 실제 작성시간과 다르게 나타나는 문제

### ISSUE THREAD

**Issue by xrabcde** [woowacourse/prolog#255]
![image](https://user-images.githubusercontent.com/56033755/130058445-f026025d-8e2f-48d1-a7b5-2db6fb5e9c97.png)

글 작성시간이 실제시간과 -9:00 차이나는 것으로 보아
UTC 타임존으로 표시되고 있는 것 같습니다...🙄

**Comment by bperhaps** [comment]
이열
