### ISSUE TITLE
post 수정에서 카테고리를 수정하려고 할 때 카테고리의 목록이 본문의 내용과 겹쳐서 보입니다.

### ISSUE THREAD

**Issue by yujo11** [woowacourse/prolog#260]
![image](https://user-images.githubusercontent.com/61097373/130179122-7ed99de2-ebca-4a8b-96a9-6d059f0830ed.png)

**Comment by yujo11** [comment]
<img width="1468" alt="스크린샷 2021-08-20 오후 1 30 35" src="https://user-images.githubusercontent.com/61097373/130179330-a06ef0fa-441a-4314-8090-fc38f342d555.png">

z-index로 우선순위위를 조절해주면 해결 되는거 같습니다람쥐~~

**Comment by xrabcde** [comment]
#254  에 있지롱

**Comment by yujo11** [comment]
헐...

**Comment by yujo11** [comment]
알려줘서 고마워 바다! 🌊🌊🌊
