### ISSUE TITLE
글 작성 시, 제목에서 일부 알파벳이 잘려 보입니다.

### ISSUE THREAD

**Issue by yujo11** [woowacourse/prolog#261]
좋은 서비스 만들어주셔서 감사합니다! 글 쓰는게 엄청 편해졌네용 👍👍👍

서비스를 사용하던 중 일부 알파벳이 잘려보이는 현상이 있어 이슈로 등록합니다!

- 아래 사진처럼 `j`, `g` 등 아래로 뻗어있는 일부 알파벳이 잘려서 보입니다.

![image](https://user-images.githubusercontent.com/61097373/130180025-4d09861d-82ad-41e6-bb32-a20a9b83ddd9.png)

**Comment by yujo11** [comment]
![image](https://user-images.githubusercontent.com/61097373/130181739-4732e73d-2e4a-4738-ba62-dd66f2ae1429.png)

일부 한글에서도 같은 현상이 일어나는거 같습니다!

**Comment by gracefulBrown** [comment]
#296
