### ISSUE TITLE
글 수정 시 메인 페이지로 리다이렉트

### ISSUE THREAD

**Issue by dusdn1702** [woowacourse/prolog#262]
안녕하세요!!! 이거 정말 멋드러지네요!!! 감사합니다 ㅎㅎㅎ

글 수정하고 잘 반영되었나 확인하고 싶은데 작성완료하면 메인페이지로 돌아가서 다시 프로필 -> Posts -> 글 찾기 과정을 반복해야 해서 조금,, 아주 조금,,, 불편하다고 느껴보았습니다..👀

작성완료 하면 자신의 Posts로 리다이렉트되면 어떨까요~?😀

**Comment by gracefulBrown** [comment]
#282 에서 작업 하겠습니다! 의견 고마워요~
