### ISSUE TITLE
제목이 긴 경우 저장 시 제목이 잘립니다.

### ISSUE THREAD

**Issue by yujo11** [woowacourse/prolog#263]
"중첩된 URL(/reservation/edit)에서 새로고침시 manifest를 불러오지 못 하는 오류" 라고 제목을 등록 했는데 작성 완료하니 아래와 같이 제목이 잘리네요ㅠㅠ 수정 페이지로 들어가도 잘린 이름까지만 표시되고 있어요!

혹시 제목에 길이 제한이 있나요? 길이 제한이 있으면 사용자가 알 수 있게 표시해주는 기능이 있으면 좋을거 같아요!

![image](https://user-images.githubusercontent.com/61097373/130180906-6357dbe5-4c5f-4652-ad70-d2f65e8067f1.png)

**Comment by bperhaps** [comment]
LOB으로 변경할지 논의 필요

**Comment by gracefulBrown** [comment]
제목의 길이를 50자로 제한했어요!
관련해서 기능이 배포되었습니다 :) 
@yujo11 제보 고마워요~~
