### ISSUE TITLE
포스트에서 뒤로 가기 시, 1페이지로 돌아가는 현상

### ISSUE THREAD

**Issue by yujo11** [woowacourse/prolog#264]
안녕하세요! 프롤로그 정말 잘 사용하고 있는데요!

다른 크루들이 작성한 학습로그를 구경하던 중 약간의 불편사항을 느낀 점이 있습니다ㅠㅠ

아래와 같이 뒷 페이지에 있는 크루들의 글을 읽고 뒤로가기 시, 다시 1페이지로 돌아가는 점인데요. 제가 원래 있던 페이지로 돌아갈 수 있으면 사용하기 훨씬 좋아질거 같아서 건의 드려봅니다! 

감사합니다!!

![Aug-20-2021 14-04-12](https://user-images.githubusercontent.com/61097373/130182080-eb6b153d-bc76-407d-99e0-7d563d95bb7c.gif)

**Comment by devhyun637** [comment]
오 이문제 발견하고 말해보려고했는데, 유조가 올려주셨군요 감사합니다 :)

**Comment by gracefulBrown** [comment]
#282 에서 작업 하겠습니다! 의견 고마워요~
