### ISSUE TITLE
orphanremoval vs cascade.REMOVE

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse/prolog#270]
두 기능에 대한 차이를 명확하게 이해한 후 엔티티 관계 맵핑을 개선한다.

**Comment by bperhaps** [comment]
orphanremoval 객체간의 연관관계가 끊겼을 때 자식 객체를 삭제하게 됩니다(JPA의 엔티티관계와 헷갈리면 안됩니다).
따라서 엔티티간의 관계로 봤을 때 oneToMany에서 연관관계의 주인이 아닌쪽의 컬렉션에서 연관관계 주인쪽의 객체를 삭제하면 delete from 쿼리가 날아갑니다. 마찬가지로 연관관계 주인쪽에서 주인이 아닌쪽을 null로 한다면, 해당 객체를 삭제하는 쿼리가 날아갑니다.

REMOVE의 경우에는 부모객체가 삭제되었을 때 자식객체를 다 날리는겁니다. 이때는 연관관계 주인이 아닌쪽의 컬렉션에서 객체를 지우더라도 객체간의 연결만 끊어질 뿐 delete 쿼리가 발생하지 않습니다.

둘의 공통점은 부모를 지울 때 자식도 다 사라지는거고, 다른점은, orphanremoval을 사용하면 자식객체(연관관계 주인 객체)의 생몀주기가 부모객체로 옮겨진다는 점이 달라집니다.

**Comment by bperhaps** [comment]
참고로 orphanremoval 만 사용하면 버그가 있다는 이야기가 있어서 다른 cascade 조건과 함게 사용하는게 아니면 사용하지 않기를 추천합니다.

**Comment by da-nyee** [comment]
우연히 이 이슈를 보게 됐는데, [제가 최근에 작성한 테코블 글](https://woowacourse.github.io/tecoble/post/2021-08-15-jpa-cascadetype-remove-vs-orphanremoval-true/)이 딱 이 내용이어서 링크 첨부하고 갑니다 🙈

**Comment by Hyeon9mak** [comment]
@bperhaps 
자세한 설명 감사합니다!! 👍 👍 👍 👍 
> **orphanremoval** - 연관관계 주인 객체를 자식, 반대 객체를 부모로 보고 관계를 형성한다. 부모 객체의 소멸과 관계 없이 자식 객체가 단 하나의 부모객체에게도 참조되지 못한다면(연결이 끊기면) 이를 고아객체로 여기고 삭제된다. (참조 되지 못하고 떠돌아다니는 더미데이터를 막기 위해서)  
> **cascacde.REMOVE** - 데이터베이스 수준 개념으로 연관관계에 대해 모른다. 참조(연결)가 끊겨도 핸들링은 없다.

두 개념 모두 객체를 DB상에서 지우는 동작으로 연관객체를 함께 지워준다는 점은 동일하고,  
연관객체간 참조를 해제하는 동작에서 차이가 발생하는 걸로 이해하고 테스트를 진행했는데 결과가 저희가 기대한거랑 다르더라구요...:sob:
다른 이슈부터 처리하고 다시 테스트 해봐야겠어요 ㅠㅠ

@da-nyee 
👍 👍 👍  저랑 웨지도 다니가 적어주신 내용으로 이해하고 테스트를 진행했는데 테스트가 뭔가 꼬였었나봐요 ㅠㅠ...

**Comment by Hyeon9mak** [comment]
개인적으로 테스트 해보니까 너잘 다니가 알려주신 내용과 동일한데 왜 prolog 프로덕션 코드에서는 다른 동작을 했는지 모르겠네요 😮

**Comment by sihyung92** [comment]
확인 결과 참조객체 삭제시 delete 쿼리가 나가는 것을 확인하여 'post에서 postTag를 제거했을 때 DB에서 delete된다'는 기능을 활용하기 위해 orphanRemoval=true로 유지하겠습니다!
