### ISSUE TITLE
태그의 길이 유효성과 alert문구

### ISSUE THREAD

**Issue by Be-poz** [woowacourse/prolog#275]
태그로 ``ConfigurationProperties``를 등록하려했으나 길이 때문인지 글 작성을 누르면 alert 는 뜨는데 아무 문구도 없이 뜨고 글작성은 되지 않습니다.  

글 수정을 누른 후에 ``ConfigurationProperties``를 등록 후에 작성완료를 클릭하면 이 때에는 그냥 완료가 됩니다만 태그는 추가되지 않은 상태로 완료 됩니다. 일관성이 없는 것 같습니다.  

태그 길이에 대한 적절한 alert가 있으면 좋을 것 같습니다.

**Comment by 0307kwon** [comment]
![image](https://user-images.githubusercontent.com/48755175/130418761-d105b690-9969-4055-af65-2060775d5cc2.png)
저도 같은 문제를 겪었습니다 ㅠㅜ 수정되어야 될거 같아요!

**Comment by gracefulBrown** [comment]
#283 이슈에서 태그 제한 변경과 알림 멘트 노출 작업을 진행하겠습니다 :) 

@Be-poz @0307kwon 제보와 보충 설명 고마워요ㅠㅠ!!
