### ISSUE TITLE
글 수정 시 드롭다운 메뉴가 마크다운 에디터에 겹쳐지는 문제

### ISSUE THREAD

**Issue by da-nyee** [woowacourse/prolog#280]
## 글 작성
![create](https://user-images.githubusercontent.com/50176238/130408700-7ad950fe-6a47-4332-a074-7cc5ebaf9246.png)

## 글 수정
![update](https://user-images.githubusercontent.com/50176238/130408339-b4d4ea1a-e6b5-42b3-817c-c459083158ef.png)

안녕하세요! 프롤로그 넘 예뻐요 ㅎㅎㅎ 잘 쓰고 있습니다 👍
다름이 아니라, 글 작성 시에는 드롭다운 메뉴가 마크다운 에디터에 겹쳐지지 않는데 글 수정 시에는 겹쳐지는 문제가 있어서 제보합니다 !

**Comment by gracefulBrown** [comment]
#269 로 해결 될 예정입니다!
@da-nyee 제보 고마워요 🙇‍♂️
