### ISSUE TITLE
마크다운으로 코드 입력시 길어지면 넘어가는 현상

### ISSUE THREAD

**Issue by DWL5** [woowacourse/prolog#285]
![image](https://user-images.githubusercontent.com/18106839/130420597-2a569a52-8888-47f9-97a0-534e54e5c20b.png)

![image](https://user-images.githubusercontent.com/18106839/130420671-90b25daa-8814-43ca-99af-029309500743.png)

에디터에서는 정상적이나 프리뷰랑 실제글에서 넘어가네요.

**Comment by da-nyee** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 무한 문자열 (?)
