### ISSUE TITLE
리버스 프록시 서버를 구축하고, 로드밸런싱을 적용한다

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#294]
현재 하나의 WAS에서 서버가 운영되고 있는데, 로드 밸런싱을 적용하기 위한 리버스 프록시서버를 구축한다.

**Comment by gracefulBrown** [comment]
빈즈토크로 관리되고 있기 때문에 일정 부하가 발생 할 경우 새로운 인스턴스가 시행되고 로드밸랜싱됩니다.
