### ISSUE TITLE
사파리에서 글 작성시 제목부분이 잘립니다.

### ISSUE THREAD

**Issue by Tanney-102** [woowacourse/prolog#296]
![스크린샷 2021-08-24 오후 1 10 23](https://user-images.githubusercontent.com/57767891/130554646-93cd642a-822b-4ef5-b41b-3f192ce87307.png)

**Comment by da-nyee** [comment]
크롬에서도 동일한 이슈가 발생합니다!

![image](https://user-images.githubusercontent.com/50176238/130558502-34db2db6-c6cf-440d-b91c-0c79e12c242b.png)
