### ISSUE TITLE
필터링 선택된 levels에 해당하는 missions만 표시한다. - (기능제안)

### ISSUE THREAD

**Issue by SunYoungKwon** [woowacourse/prolog#313]
필터링 시 선택된 levels이 있다면 해당 missions만 노출시키는 것이 어떨까요?
레벨3 프로젝트를 선택하고 나면 missions에는 레벨3 프로젝트에 해당하는 미션만 나타나는 것이 더 사용에 용이할 것 같습니다. 미션의 개수가 많아 원하는 미션을 찾아 선택하기 쉽지 않네요ㅠ

<img src="https://user-images.githubusercontent.com/45230497/130882839-1f16babf-96ef-49c9-b080-be433c5490ef.png" alt="필터링 levels 선택" width="400" />

<img src="https://user-images.githubusercontent.com/45230497/130882851-782ba227-e5ec-4823-868f-3b45a161cfc1.png" alt="필터링 missions 선택" width="400" />

**Comment by sihyung92** [comment]
진행상황 공유 - 
1. 필터는 filters API에서 한번에 모든 코드를 주도록 설계 되어있음 (GET /filters, 파라미터 없음)
2. 미션에 따른 분류를 하기 위해선 API 재설계가 필요함(mission Id를 인자로 전달)
3. 하지만 filterResponse에서 mission에 레벨정보가 포함되어 있기 때문에 프론트에서 분류도 가능할 것으로 보임!
```
{
  "levels" : [ {
    "id" : 1,
    "name" : "레벨1"
  }, {
    "id" : 2,
    "name" : "레벨2"
  } ],
  "missions" : [ {
    "id" : 1,
    "name" : "지하철 노선도 미션 1",
    "level" : {
      "id" : 1,
      "name" : "레벨1"
    }
  } ],
  "tags" : [ ]
}
```

결론 -  미션의 레벨 정보를 기반으로 프론트에서의 필터링을 제안함!
