### ISSUE TITLE
cloudwatch 대시보드 구축을 한다

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#325]
Elastic Beanstalk에는 이미 모니터링 옵션도 제공해준다.
따라서 모니터링보다는 로그 위주로 구축한다.

**Comment by qhals321** [comment]
### 클라우드 화면 예시(프롤로그 dev서버)
![image](https://user-images.githubusercontent.com/63535027/132799227-a1fe0911-1142-4eec-9988-1c6f8f384d46.png)
![image](https://user-images.githubusercontent.com/63535027/132799269-1c95ca55-f6e7-4b93-847b-23cd6ce5e5b4.png)
![image](https://user-images.githubusercontent.com/63535027/132799295-5eb0cde4-485d-4a53-b4c8-199d66014a22.png)
