### ISSUE TITLE
@AuthMemberPrincipal에서 Member 도메인이 아닌 전용 DTO 를 이용하면 좋을 것 같습니다!

### ISSUE THREAD

**Issue by qhals321** [woowacourse/prolog#347]
이번에 MemberTags을 개발하다 Member 도메인 관련 문제점에 직면하게 되었습니다!

### 문제 발생
MemberTags 는 Member가 관리하면 좋을 것 같다는 생각으로 Member를 연관관계 주인으로 1:N 로 만들게 되었습니다.
이제 스터디로그를 등록, 수정, 삭제할 때 자동으로 멤버의 멤버태그도 변화를 주려고 계획했습니다!
다음은 스터디로그 등록 코드입니다!
```
    private PostResponse insertPost(Member member, PostRequest postRequest) {
        Tags tags = tagService.findOrCreate(postRequest.getTags());
        Mission mission = missionService.findById(postRequest.getMissionId());

        Post requestedPost = new Post(member,
                postRequest.getTitle(),
                postRequest.getContent(),
                mission,
                tags.getList());

        Post createdPost = postRepository.save(requestedPost);
        member.addTags(tags);  <<== 태그를 추가하는 부분

        return PostResponse.of(createdPost);
    }
```
위 처럼 Member 안에 있는 태그 정보를 dirty checking 을 통해 변경이 일어날 수 있도록 만들었습니다!
하지만, Member가 영속성 컨텍스트에서 더이상 관리하지 않는 객체이기 때문에 더티 체킹이 불가능합니다!
(ArgumentResolver에서 서비스를 이용해 Member를 가져오지만 실제 서비스와 트랜잭션이 분리)

다시 영속성 컨텍스트에 등록을 하려면 동일한 쿼리를 다시 한 번 날려야 했습니다ㅠ...
그래서 아예 서비스로 들어오는 Member는 헷갈리지 않게 전용 DTO로 가져오는 건 어떨지 의견을 내봅니다!!

해당 DTO는 JWT에 담겨있는 memberId, authority(생기면 좋을 것 같은!) 정보를 가지고 있는 DTO 를 생각중입니다!

**Comment by bperhaps** [comment]
동의합니다. 도메인이 Controller에 침범하는것은 전통적인 web layer에 어긋납니다.

물론, JPA에서도 OSIV를 통해서 엔티티의 영속성 관리 생명주기를 Service가 아닌, Controller까지 끌어와서 presentation layer에서 수정은 불가능하고 조회만 가능하도록 하고 서비스에서는 더티체킹이 가능하도록 하는 방법을 제안하고는 있습니다만, 이는 OSIV를 또 다시 공부해야하는 러닝커브가 있고 서비스의 전체적인 복잡도를 올린다고 생각합니다.

따라서 Member를 위한 DTO를 만들어서 관리하는것에 찬성하는바 입니다.

**Comment by seovalue** [comment]
저도 위 손교수님이 남겨주신 첫번째 줄과 동일한 이유로 @AuthMemberPrincipal에서 전용 DTO 이용하는 거 좋다고 생각해요! 👍

**Comment by sihyung92** [comment]
Agree
