### ISSUE TITLE
[리포트] 리포트 작성 시, 학습로그 역량 그래프를 관리하는 기능을 구현한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#366]
# 기능
- [x] 리포트 작성 시 역량 그래프 중 표시 여부를 선택할 수 있다.
- [x] 리포트 작성 시 역량 그래프에 가중치를 설정한다. 가중치는 100% 만점 기준으로 사용자가 스스로 결정한다.
  - 리포트 역량 그래프 가중치는 `개별 / 전체 * 100` 로 구한다.
  - 사용자는 자신이 원하는 숫자를 입력할 수 있다.
  - 1~10사이의 정수로 입력할 수 있다.
- [x] 리포트에는 역량그래프 및, 각 역량에 포함된 학습로그 조회가 가능하다.
- [x] 리포트 페이지에서 역량을 클릭하면, 해당 역량이 선택되었음을 알 수 있다.
  - [x] 선택하지 않은 역량들은 회색으로 바뀐다.
  - [ ] 선택한 역량의 크기가 커지고, 어떤 역량인지 그래프에 표시된다.
  - [x] 취소 버튼을 선택하여 아무것도 선택되지 않은 초기 화면으로 돌아간다.

# 디자인 시안
- 가중치 관리 화면
<img width="661" alt="스크린샷 2021-08-19 오후 6 50 43" src="https://user-images.githubusercontent.com/59258239/130048431-56a37ed7-628d-43f9-a731-5292ec3bd8fd.png">

**Comment by sunhpark42** [comment]
범주가 아닌 그래프와의 상호작용은 별도 이슈 생성하겠습니다.
