### ISSUE TITLE
ElasticSearch를 고도화 한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#386]
## 작업 목록
- [ ] #397
- [ ] #398

**Comment by seovalue** [comment]
## 1. 모니터링
엘라스틱 서치 서버의 상태를 모니터링할 수 있는 대시보드를 만들기.
중점: 현재 서버 상태랑 클러스터 & 노드 상태를 관제할 수 있는 시스템이 구축되어있어야한다. 

## 2. 로컬에 엘라스틱 서치 설치
도커 볼륨을 사용하면 불안정할 수 있다.
로컬에서 엘라스틱 서치를 직접 설치해서 지금과 동일한 환경이 구성되도록 하기
