### ISSUE TITLE
사용자 리액션 기능을 검토한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#391]
## 사용자 리액션 종류
- 찜 or 담아두기 or 스크랩
- 좋아요 ~~or 따봉 or 붐업~~

## 검토 체크리스트
- [x] 유사한 서비스의 사례를 조사한다
- [x] 사용자 리액션 기능의 목적을 정리한다
  - 리액션을 통해 어떤 효과를 기대하는지
  - 리액션을 통해 어떤 부가적인 기능을 제공 할 수 있을 지
    - ex) 매주 좋아요 통계를 메인 화면에 노출하기  
- [x] 할 일들의 목록을 정리한다

**Comment by sihyung92** [comment]
# 회의 주제

- 사용자 리액션 종류를 결정하고, To Do 목록을 작성한다.

# 개요

1. 월요 주간회의에서 나온 사용자 리액션의 필요성   
  - 특정 학습로그들을 표시해두었다가, 나중에 다시 보고 싶다. (찜)
  - 댓글을 통해 질문 / 답변 혹은 피드백을 받고 싶다.
  - 하트나 좋아요 개수를 통해 사용자 반응을 확인하고 싶다.
 
-> 어떤 목표를 달성할 지 결정하고, 적절한 사용자 리액션을 추가한다.

# 한 번 생각하고 와주세요!

1. 개요의 3가지 목표중 가장 필요하다고 생각하는 **목표를 하나 정해주세요**! (혹은 기타 의견)
2. 그 목표에 필요한 사용자 리액션을 활용하고 있는 서비스 사례를 **1가지 이상 조사해주세요**! 
3. 붐업

# 회의 순서
1. 각자 생각하는 목표와, 유사한 서비스 사례 소개 + 어떤 사용자 리액션을 추가할지 토의 후 결정
2. 1의 결정을 바탕으로 Todo List 작성 (일정, 공수, 내용, 업무 분담)

# 체크리스트
- [ ]  유사한 서비스의 사례를 조사한다
- [ ] 사용자 리액션 기능의 목적을 정리한다
  - 리액션을 통해 어떤 효과를 기대하는지
  - 리액션을 통해 어떤 부가적인 기능을 제공 할 수 있을 지
- [ ] 투두리스트를 정리한다
---

# 회의록

**Comment by sihyung92** [comment]
# 시나리오 회의
- 추가사항 : 최대한 컴포넌트를 재활용 할 수 있는 방향으로! (편하게 편하게)
- 추가로 생각해봐야할 사항 
  - 읽음 기능에 시간 추가하기
  - 조회수 기능에 어뷰징 방지하기 
# 좋아요 기능
## 학습로그 상세페이지
   ### 등록기능
   1. 로그인 사용자
    - 로그인 한 사용자가 학습로그 상세페이지에서 좋아요를 누르면
    - 좋아요 카운트가 올라가고, 눌렀다는 티가 난다
   2. 비로그인 사용자
    - 비로그인 사용자가 학습로그 상세페이지에서 좋아요를 누르면
    - 로그인 하라는 안내메시지가 출력된다.
     
    ### 취소기능
    - 로그인 한 사용자가 학습로그 상세페이지에서 눌러져있는 좋아요를 다시 누르면
    - 좋아요 카운트가 1 내려가고, 안 누른 티가 난다
    
    ### 조회 기능
    1. 로그인 사용자
      - 로그인 한 사용자가 학습로그 상세페이지에 들어왔을 때
      - 기존에 좋아요를 눌렀었다면
      - 눌렀다는 티가 나고, 숫자와 함께 표시된다
      - 기존에 좋아요를 안 눌렀다면
      - 안 누른 티가 나고, 숫자와 함께 표시된다
    2. 비로그인 사용자
      - 비로그인 사용자가 학습로그 상세페이지에 들어왔을 때
      - 좋아요가 안 누른 티가 나고, 숫자와 함께 표시된다.
       
## 학습로그 목록 페이지
 조회 기능
 1. 로그인 사용자
   - 로그인 한 사용자가 학습로그 목록 페이지에 들어왔을 때 
   - 기존에 좋아요를 눌렀다면
   - 눌렀다는 티가 나고, 좋아요 숫자가 표시된다.
   - 기존에 좋아요를 안 눌렀다면
   - 안 누른 티가 나고, 좋아요 숫자가 표시된다.
 2. 비로그인사용자
   - 비로그인 사용자가 학습로그 목록 페이지에 들어왔을 때
   - 좋아요 안 누른티가 나고, 좋아요 숫자가 표시된다.
   
# 스크랩 기능
## 학습로그 상세페이지
  ### 등록기능
  1. 로그인 사용자
  - 로그인 한 사용자가 학습로그 상세페이지에서 스크랩을 누르면
  - 스크랩 버튼이 눌렀다는 티가 난다
  2. 비로그인 사용자
  - 비로그인 사용자가 학습로그 상세페이지에서 스크랩을 누르면
  - 로그인 하라는 안내메시지가 출력된다.
   
### 취소기능
  - 로그인 한 사용자가 학습로그 상세페이지에서 눌러져있는 스크랩 버튼을  다시 누르면
  - 안 누른 티가 난다
      
### 조회 기능
1. 로그인 사용자
  - 로그인 한 사용자가 학습로그 상세페이지에 들어왔을 때
  - 기존에 스크랩을 눌렀었다면
  - 눌렀다는 티가 난다.
  - 기존에 스크랩을 안 눌렀다면
  - 안 누른 티가 난다.
2. 비로그인 사용자
  - 비로그인 사용자가 학습로그 상세페이지에 들어왔을 때
  - 안 누른 티가 난다.
       
## 프로필 스크랩 페이지
  로그인 한 사용자만 접근 가능하다. 
  ### 목록 조회 기능
  - 로그인한 사용자가 프로필 스크랩 페이지를 들어오면,
  - 기존에 스크랩을 누른 목록이 표현된다.
  - 페이지네이션이 적용된다.
  
  ### 목록 상세 조회 기능
  - 로그인한 사용자가 프로필 스크랩 페이지를 들어와서
  - 스크랩 목록 중 하나를 클릭하면
  - 상세페이지로 이동한다.
  
  ### 스크랩 취소 기능
  - 로그인한 사용자가 
  - 스크랩 목록 중 하나에 마우스를 hover하면
  - 스크랩 취소 버튼이 노출되고
  - 취소 버튼을 누르면
  - 목록에서 제외된다.

# 읽음 기능
## 학습로그 상세페이지
### 등록 기능 
1. 로그인 사용자
  - 로그인 한 사용자가 학습로그 상세페이지를 들어가면
  - 읽음 상태 처리가 된다.
  
2. 비로그인 사용자는 제외
    
       
## 학습로그 목록 페이지
조회 기능
1. 로그인 사용자
  - 로그인 한 사용자가 학습로그 목록 페이지에 들어왔을 때 
  - 기존에 읽음상태인 글은
  - 읽은 티가 난다
  - 기존에 안 읽은 상태인 글은
  - 안 읽은 티가 난다.
2. 비로그인 사용자는 제외
     
# 조회수 기능
## 학습로그 상세페이지
### 등록 기능
- 사용자가 학습로그 상세 페이지에 들어왔을 때
- 조회수가 1 상승한다.

### 조회 기능
- 사용자가 학습로그 상세 페이지에 들어왔을 때
- 조회수가 노출된다.

## 학습로그 목록페이지
### 조회기능 
- 사용자가 학습로그 목록 페이지에 들어왔을 때
- 각 학습로그의 조회수가 노출된다.
