### ISSUE TITLE
배포 프로세스를 개선한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#393]
## 검토 목록
- [ ] 할 일 목록을 만들기

## 관련 이슈
- #379
- #373 
- #294 
- #295

**Comment by qhals321** [comment]
## 회의 일정

미정

## 회의 주제

프롤로그 배포 프로세스 공유 및 개선 방안

## 관련 이슈

- #393
- #379
- #373
- #294
- #295

## 현재 프로세스

핵심** AWS ElasticBeanstalk을 이용.

- ElasticBeanstalk이란?

    → EC2 생성, 디비 생성 및 구축, 부하분산 및 로드밸런싱, 무중단 배포, 모니터링 등 배포 및 운영에 필요한 대부분의 기능들을 손쉽게 사용할 수 있게 제공해주는 서비스

관련 기능을 더 자세히 보고 싶다면 

[https://ap-northeast-2.console.aws.amazon.com/elasticbeanstalk/home?region=ap-northeast-2#/environment/configuration?applicationName=pro-log&environmentId=e-nji2sekzvh](https://ap-northeast-2.console.aws.amazon.com/elasticbeanstalk/home?region=ap-northeast-2#/environment/configuration?applicationName=pro-log&environmentId=e-nji2sekzvh)

구성을 확인해주세요!

## 이번 회의 목표

- 백앤드 모두가 대략적인 배포 및 운영 프로세스 지식 획득
- 배포 및 운영에 관한 다른 시야 공유
- 추가적으로 적용하고 싶거나 현재 프로세스에서 개선해야 할 부분 공유

**Comment by qhals321** [comment]
## 최종 의견
- feature 전용 서버 CD (추가 기능)
- 성능 뿐만이 아니라 기능적으로 모니터링을 하면 좋겠다. (태그가 몇 번 클릭이 되었는지, 어떤 검색어가 가장 많은지 등등) -> n click by 네이브라운 (추가 기능) -> 구글 애널리틱스

- 엘라스틱 서치 서버 모니터링 - 조앤, 나봄
- 문서화 필요 - 나봄
- 모니터링 지표 정리 - 웨지
- pr 확인 및 코드 스멜 확인 (CI) - 너잘
