### ISSUE TITLE
studylog 테스트가 깨지는 문제.

### ISSUE THREAD

**Issue by bperhaps** [woowacourse/prolog#418]
현재 몇몇 studylog 인수테스트가 실패합니다.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/33603557/134310393-c9712138-1bb7-4a04-b26a-ee7607eea56a.png">

search resolver에서 기본 page size가 10으로 돼어 있어서 발생합니다.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/33603557/134310447-ec783dbf-8734-445f-bf94-eaffa8c0b723.png">

테스트의 완수조건을 totalsize 로 하던지, defaultValue를 20으로 늘리던지, 인수테스트에서 size 조건을 직접적으로 명시하는등의 조치가 필요할듯 합니다.

**Comment by seovalue** [comment]
ohoh default는 원래 10이 맞습니다 ㅎㅎ 테스트 완수조건을 변경해서 fix해둘게요!

**Comment by seovalue** [comment]
<img width="430" alt="스크린샷 2021-09-23 오전 6 59 40" src="https://user-images.githubusercontent.com/48412963/134427837-601a3929-3385-4f99-958e-7163f3cb3922.png">

요 부분은 제가 잘 모르겠어서ㅜㅜ 냅두구 검색 관련 테스트 깨지는 것은 https://github.com/woowacourse/prolog/pull/412 해당 피알에 fix해서 추가해두었습니다 ~~

**Comment by qhals321** [comment]
에구 이제 확인했네요ㅠ
기존에 존재했던 Post 작성 Given 이 바뀌어 있었네요!
바뀐 스펙에 맞게 다시 테스트 작성했습니다~!
