### ISSUE TITLE
/member/me 를 [GET, PUT] /member/{username} 으로 변경한다.

### ISSUE THREAD

**Issue by bperhaps** [woowacourse/prolog#443]
#258 과 관련이 있습니다.

member/me 로 호출하던 API를 /member/{username}으로 변경해 주시면 됩니다. 해당 머지가 완료되면 노티 부탁 드립니다.

**Comment by Hyeon9mak** [comment]
`develop <- feature/reports` PR 충돌 해결 과정에서 우선적으로 머지 시켰습니다.

**Comment by devhyun637** [comment]
닉네임 수정은 해당 API 적용했습니다!
