### ISSUE TITLE
검색이 안되는 이슈

### ISSUE THREAD

**Issue by Be-poz** [woowacourse/prolog#456]
지금 검색해도 먹히지가 않습니다~!

**Comment by seovalue** [comment]
![](https://files.slack.com/files-pri/T02A1SS2C7N-F02GR83DJHJ/_______________________________2021-10-05______________5.58.08.png)

**Comment by seovalue** [comment]
![image](https://user-images.githubusercontent.com/48412963/136004929-652eb2f8-bb96-40e7-ab7f-41672f605c61.png)

Elasticsearch 관련 인스턴스가 현재 불안정한 것으로 보입니다.
로그 확인이 아직 어려워서 보류 중입니다.

**Comment by seovalue** [comment]
@Be-poz 이슈 남겨주셔서 감사해요! 다시 검색 가능하도록 fix 완료했습니다 :-) 해당 이슈는 클로즈할게요!
