### ISSUE TITLE
[리포트] 역량 기능 개선을 한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#488]
- [x] 상위 역량 삭제 시 하위 역량 전체 삭제 가능하도록 변경
  - 현재는 하위 역량이 있는 경우 삭제할 수 없음
- [x] 등록된 역량이 없는 경우 [역량 초기 설정] 버튼을 노출하기
  - [x] 프론트엔드 / 백엔드 버튼 두가지 노출
  - [x] API 작업 필요
- [x] 역량 목록 > 역량 글씨와 설명 글씨의 글씨체 크기 같게 수정하기

**Comment by Hyeon9mak** [comment]
- [ ] 멤버별 역량 조회 API의 memberId를 memberName 으로 변경
  - 다른 멤버 기능의 경우 memberName을 사용하고 있어 헷갈린다는 의견 제시됨

**Comment by Hyeon9mak** [comment]
초기 역량을 어떻게 관리하는가?

- 서비스 코드로 갖고 있는다.
  - 초기 역량에 변화가 일어날 때마다 재배포가 되어야 한다.
- Csv 파일로 관리한다. (채택)

초기 역량을 어떻게 요청하는가?

- 프론트가 초기 역량을 지닌채로 백엔드에 요청한다.
- 백엔드가 초기 역량을 지닌채로 프론트가 요청한다. (채택)

---

백엔드가 Csv 파일로 백엔드/프론트엔드 초기 역량을 소유하고, 프론트가 API를 통해 전체 초기 역량 등록을 요청한다.
