### ISSUE TITLE
h2 및 mysql 모두에서 범용적인 DB 스키마 파일로 수정한다

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#51]
- 이슈 : 로그인 팀에서 작업 중 인 브랜치에서 mysql 전용 문법으로 인해 오류가 발생
- 해결 : mysql과 h2 범용적인 문법으로 수정
- 기타 : varchar(65535)타입으로 생성하면 TEXT 타입으로 생성하라는 오류 발생, post 테이블의 content 칼럼의 타입을 varchar(65535) 에서 text로 수정, drop table 순서로 인해 발생하는 외래키 오류 수정
※ text : 65535 byte ~ 64kb의 가변 문자 타입

**Comment by pkeugine** [comment]
@sihyung92 @bosl95 @soulgchoi @gracefulBrown 

현재 테이블 스키마 컨벤션이 정해지지 않아서 해당 부분도 합의 필요.
정해지는대로 fix/schema-edit 브랜치에 반영할 예정.

건의:
* 이름 소문자 (테이블명, 컬럼명 등)
* 그 외 대문자

예시:
```sql
CREATE TABLE IF NOT EXISTS postTag (
    id BIGINT NOT NULL AUTO_INCREMENT,
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT post_id
    FOREIGN KEY (post_id)
    REFERENCES post (id),
    CONSTRAINT tag_id
    FOREIGN KEY (tag_id)
    REFERENCES tag (id)
);
```

**Comment by sihyung92** [comment]
찬성합니당당당
