### ISSUE TITLE
[리포트] 역량 그래프에서 그래프 이미지 영역에 상호작용을 추가한다.

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse/prolog#540]
- [ ] 그래프 클릭 시 해당하는 역량을 표시한다.
- [ ] 그래프에 마우스를 가져다 놓으면 포함된 역량을 표시한다.
- [ ] 선택된 역량의 그래프의 크기를 확대한다.

**Comment by gracefulBrown** [comment]
진행되지 않고있는 이슈입니다. 추후 필요 시 재생성 후 진행합니다.
