### ISSUE TITLE
[리포트] 대표 리포트가 첫번째로 오지 않는 버그

### ISSUE THREAD

**Issue by devhyun637** [woowacourse/prolog#571]
리포트가 총 5개 일때에는 대표 리포트가 응답에서 첫 번째로 오는데, 
리포트가 6개가 되는 순간 첫번째 페이지가 아닌 두 번째 페이지의 첫 응답으로 오고 있습니다.

### 버그 상황
요청 `http://localhost:5000/devhyun637/reports?type=all&page=1&size=4`
응답 (첫번째가 `represent: true가 아님`)
<img width="774" alt="스크린샷 2021-11-01 오후 9 57 29" src="https://user-images.githubusercontent.com/59258239/139675106-077025f2-2735-4823-b89d-45068b85ef83.png">

요청 `http://localhost:5000/devhyun637/reports?type=all&page=2&size=4`
응답 (첫번째가 `represent:true 임`)
<img width="780" alt="스크린샷 2021-11-01 오후 9 58 39" src="https://user-images.githubusercontent.com/59258239/139675249-34990bdd-c170-458d-9d71-324afda5d201.png">

**Comment by sihyung92** [comment]
며칠전에 민성쿤이 머리싸매던게 요거였군

**Comment by sunhpark42** [comment]
리포트 기획 변경으로 인한 QA 이슈 close 하겠습니다~
