### ISSUE TITLE
[리포트] 리포트에 선택 취소한 역량이 이미 학습로그 역량으로 포함되어 있을 때 오류 

### ISSUE THREAD

**Issue by devhyun637** [woowacourse/prolog#572]
### 상황
1. 리포트의 역량을 A, B, C, D, E를 선택한다.
2. 1번째 학습로그의 역량에 A, B, C, D, E를 선택한다.
3. 리포트 역량에서 A, B를 삭제한다.
4. 리포트를 등록한다.
5. 오류가 발생한다.

<img width="501" alt="스크린샷 2021-11-01 오후 10 15 30" src="https://user-images.githubusercontent.com/59258239/139677433-c8fd3fba-2a27-426e-b9ef-a8896d702c14.png">

**Comment by devhyun637** [comment]
현재 API 응답에 따른 에러처리는 반영은 했지만, 로직을 어떻게 구현해야 할지에 대한 논의가 필요합니다.

현재가지고있는 문제들입니다.
문제 1. 스넥바의 위치가 스크린 하단이 아닌, 이상한 위치에 존재한다. => alert로 대체
문제 2. 선택되지 않은 역량을 다시 삭제하려면 `사용자가 역량 그래프에서 재선택 -> 학습로그에 등록된 역량을 삭제 -> 역량 그래프에서 재삭제`의 과정이 필요한데, 이 흐름에 대해서 다같이 이야기를 하면 좋을 것 같아서 보류하겠습니다.
문제 3. 리포트를 수정할 때와 리포트를 등록할 때 동일한 상황에 대한 에러임에도 불구하고, 응답해오는 에러 응답 코드가 `4011(새 리포트 등록), 4010(리포트 수정)`으로 달라서 통일할 필요가 있을 것 같습니다.

코드 작성은 끝났는데, 위에 대한 문제가 끝나면 논의 후 수정해서 PR을 작성하겠습니다.

**Comment by sunhpark42** [comment]
리포트 기획 변경으로 인한 QA 이슈 close 하겠습니다~
