### ISSUE TITLE
리포트 페이지 > 스크롤 바 표시 건의

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse/prolog#575]
![image](https://user-images.githubusercontent.com/37354145/140236027-4211a685-3db0-4ab7-a658-6046bfb86533.png)

역량 그래프에서 스크롤이 가능하다는게 표시되면 더 좋을거 같아요!!
그래프 상에선 5개가 보이는데, 표에선 3개 밖에 안보여서 순간 멈칫 🥲

**Comment by gracefulBrown** [comment]
UI 논의 시 고려하겠습니다.
