### ISSUE TITLE
[역량 페이지] 역량 추가시 디폴트 색상을 랜덤으로 변경하는 기능 건의

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#576]
![image](https://user-images.githubusercontent.com/51393021/140236117-a949581f-84f4-4019-99cb-0e1b5fed0ee6.png)
![image](https://user-images.githubusercontent.com/51393021/140236132-9b140619-628d-4217-80c8-e76923aa914c.png)

현재 역량 생성시 색상이  #f6d7fe로 고정되어 있습니다. 역량 명과 설명을 추가하고 확인을 누르면 중복색상으로 인하여 색상을 한번 바꾸어 주어야 합니다. '역량 추가'를 할 때 기본 설정되어있는 색상이 #f6d7fe 하나로 고정되어있는 것이 아니라 랜덤하게 변경되는 기능을 건의합니당

**Comment by gracefulBrown** [comment]
기능 롤백으로 인해 재배포 후 검토하겠습니다.
