### ISSUE TITLE
[역량 페이지] 역량 초기화 기능 건의

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#577]
프론트로 지원하려다 실수로 백엔드로 지원한 사람처럼 클릭 실수를 한 사람도 있고 저처럼 심심해서 다 삭제해본 사람이 있을 수도 있다 생각함니다!
역량 초기화 기능을 만들어 초기 선택화면으로 돌아갈 수 있도록 지원하는 건 어떨지요? 
![image](https://user-images.githubusercontent.com/51393021/140236505-675d472d-d925-43af-8351-94fce430186a.png)

**Comment by devhyun637** [comment]
역량 초기화 기능은 조금 더 재고해보기로 했습니다!,!
