### ISSUE TITLE
[역량 페이지] 자식역량 추가시 '추가' 버튼을 누르면 역량 이름으로 포커스 이동

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#578]
![image](https://user-images.githubusercontent.com/51393021/140236795-d50e917b-1799-409a-adc0-34eb085f968e.png)
현재 자식역량을 추가할 때, 한번에 포커스가 이동하지 않아 저같은 키보드 의존자 한테는 약간의 번거로움이 있습니다. 탭키를 눌러봐도 바로 넘어가지 않아 '탭키로는 이동할 수 없구나' 하는 인식이 들었습니다 **(작정하고 해보니 tab키를 세 번 클릭하면 이름 탭으로 이동하네요)**
추가 버튼을 눌렀을 때 자동으로 포커싱 되면 좋을 것 같습니닷!

**Comment by gracefulBrown** [comment]
역량 ui 개편 후 필요시 재생성 하겠습니다.
