### ISSUE TITLE
[리포트 페이지] 리포트에서 역량 항목을 클릭하지 않았을 땐 리셋버튼 비활성화

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#579]
![image](https://user-images.githubusercontent.com/51393021/140237239-b6a2513c-8dc9-49b2-a409-4a68f311bfe1.png)
리셋버튼이 있는데 내 리포트 가중치를 초기화 한단건가? 뭐가 초기화 된단거지? 알쏭달쏭 했었습니다
역량 항목을 누르고 나서야 아하 이거구나 했는데요, 역량 항목을 클릭하지 않았을 땐 reset 버튼을 비활성화 하는게(클릭해도 동작 안 할 것 같은 재질) 어떨까 건의합니다!

**Comment by sunhpark42** [comment]
리포트 기획 변경으로 인한 QA 이슈 close 하겠습니다~
