### ISSUE TITLE
[리포트 페이지] 역량을 추가한 후, 기존 레포트를 수정하면 새로 추가한 역량이 나타나지 않는 현상

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#580]
![image](https://user-images.githubusercontent.com/51393021/140238131-b41ca437-d8cc-4794-b711-c6aded5950b3.png)
현상은 다음과 같습니다~~!

1. 웾웾 리포트를 작성함
2. 새로운 역량을 추가함
3. 웾웾리포트를 수정함
4. 웾웾리포트 수정화면에선 새로 추가한 역량을 볼 수 없음

버그인지 아닌지 알쏭달쏭하여 제보합니다람쥐

**Comment by sunhpark42** [comment]
리포트 기획 변경으로 인한 QA 이슈 close 하겠습니다~
