### ISSUE TITLE
[리포트 페이지] 리포트를 먼저 만들고 역량을 이후에 만들면 리포트 수정 시 역량이 뜨지 않음

### ISSUE THREAD

**Issue by qhals321** [woowacourse/prolog#581]
리포트를 먼저 만들고 난 뒤 역량을 만들어봤습니다!
리포트 수정 해서 해당 역량을 추가하려하면 해당 역량이 뜨지 않네요~!
해당 역량이 뜨면 좋을 것 같습니다!

![image](https://user-images.githubusercontent.com/63535027/140238115-39b3f4f3-af8a-4098-83a9-e8a2aa0149f9.png)

**Comment by sunhpark42** [comment]
리포트 기획 변경으로 인한 QA 이슈 close 하겠습니다~
