### ISSUE TITLE
[리포트 페이지] 리포트에서 역량을 클릭했을 때, 해당 역량과 연관된 학습로그만 필터링 하는 기능

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#582]
![image](https://user-images.githubusercontent.com/51393021/140238534-b32b2c92-0ecb-48f4-bf24-98ef05319d3a.png)
그래프 최고임니다 서니 짱짱짱짱
역량 그래프에서 역량을 클릭했을 때 목적이 모호하다고 느꼈어요 하이라이트 되긴 하는데.. 끝인가?_?  하는 늬낌
하지만 이미지 처럼 클릭했을 때 아래 학습로그 목록이 필터링 되면 충분히 목적성 있는 기능일 것 같다고 느꼈습니당

**Comment by devhyun637** [comment]
쉽지않군요.. 이건 제 담당이라서 제가 하겠습니다.

**Comment by sunhpark42** [comment]
리포트 기획 변경으로 인한 QA 이슈 close 하겠습니다~
