### ISSUE TITLE
[리포트 페이지] 1페이지가 아닌 리포트를 대표 리포트를 설정하면 최상단 노출이 안됨

### ISSUE THREAD

**Issue by qhals321** [woowacourse/prolog#583]
리포트가 2 페이지가 넘어가고 2 페이지에 있는 리포트를 대표 리포트를 설정했는데 2 페이지에 그대로 남아있네요!
1페이지 최상단으로 노출되면 좋을 것 같습니다!

![image](https://user-images.githubusercontent.com/63535027/140238624-775903e4-1215-4cbb-a691-ae9e6c3e1682.png)
![image](https://user-images.githubusercontent.com/63535027/140238742-7bbadb96-0e00-4f0f-8e44-e03f6a7bf171.png)

**Comment by sunhpark42** [comment]
#571 이슈와 중복
