### ISSUE TITLE
[리포트 페이지] 설명란의 최대 글자수를 넘겨서 입력할 수 있는 현상 & 그 이후 저장해도 아무 오류메시지가 출력되지 않는 현상

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#584]
![image](https://user-images.githubusercontent.com/51393021/140239101-eadfa787-43fa-4b5c-baf9-606987ea3772.png)
매드 리포터 웨지는 디스크립션을 150자 넘겨 작성할 수 있답니다 그리고 저장해도 아무 에러메시지가 출력되지 않는다는 것것것

**Comment by devhyun637** [comment]
오우.. 수정하겠습니다.

**Comment by devhyun637** [comment]
API가 분리되면 상황에 따른 에러코드를 받아서 처리하면 좋을 것 같습니다. 프론트엔드에서 처리하고 일단 이슈는 클로즈 하겠습니다.

**Comment by devhyun637** [comment]
새로운 리포트를 작성했을 때는 글자수가 150글자가 넘으면 error-code가 4012로 나오는데, 
리포트 수정시에는 에러코드 4010으로 `리포트를 업데이트 하는데 실패했습니다.`로 나오네요.. ㅠㅠ

수정시에도 동일한 에러코드로 보내주시면 감사하겠습니다!

**Comment by bperhaps** [comment]
@devhyun637 넵!!!

**Comment by gracefulBrown** [comment]
에러코드 업데이트 이슈는 https://github.com/woowacourse/prolog/issues/593 에서 이어서 진행하겠습니다.
