### ISSUE TITLE
[리포트] 리포트 생성시 학습로그에 역량 추가시 자식 역량이 나타나지 않는 이슈

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse/prolog#588]
![](https://user-images.githubusercontent.com/67677561/140239759-c340f38d-8233-4808-ac40-f55034df6091.png)

![](https://user-images.githubusercontent.com/67677561/140239880-63ef8dcb-fd00-409b-8913-d0b2b2fc9727.png)

자식역량이 등록되어 있으나, 학습로그에 역량 추가시 자식 역량이 나타나지 않습니다.

**Comment by gracefulBrown** [comment]
롤백되어 다시 기능 구현중입니다. 기능 구현 후 다시 확인하겠습니다
