### ISSUE TITLE
백엔드 에러코드를 업데이트한다.

### ISSUE THREAD

**Issue by devhyun637** [woowacourse/prolog#593]
현재 어떤 에러가 있는지 파악하기 어려워, 프론트에서 에러핸들링하는데 어려움이 있습니다.
자기소개서 쓰고나서 시간되실때 해주시면 최고~~!!

https://github.com/woowacourse/prolog/wiki/%EC%97%90%EB%9F%AC-%EB%AA%A9%EB%A1%9D

**Comment by sihyung92** [comment]
네

**Comment by gracefulBrown** [comment]
https://github.com/woowacourse/prolog/issues/584#issuecomment-960637053

**Comment by gracefulBrown** [comment]
추가로 진행되지 않아서 close 하고 추후 필요시 재등록합니다.
