### ISSUE TITLE
리포트 > 그래프에서 역량을 선택하지 않은 경우 수정 불가

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#597]
- 수정 시 그래프에서 모든 역량을 해제한 후 수정을 할 경우 수정이 불가능(안내 메시지 뜨지 않음)
![image](https://user-images.githubusercontent.com/46308949/140669498-bc21c038-221a-45d4-b3c3-ecb7208a7767.png)

**Comment by sunhpark42** [comment]
무슨 안내메세지를 추가해야할까요?

**Comment by gracefulBrown** [comment]
롤백되어 무효화 되었습니다. 기능 재구현 후 확인하겠습니다.
