### ISSUE TITLE
포스트 작성 시 카테고리, 태그 선택 할 수 있게 한다.

### ISSUE THREAD

**Issue by bosl95** [woowacourse/prolog#60]
## 요구 사항
- 포스트 작성 화면에서 태그/카테고리를 선택할 수 있도록 한다.
- 포스트 작성 시 태그, 카테고리 정보도 함께 될 수 있도록 한다.

## 필요 작업
- [x] 태그/카테고리 조회 API 만들기: 백엔드
- [x] API를 활용하여 태그/카테고리 선택할 수 있도록 하기: 프론트엔드
- [x] 포스트 작성 시 태그, 카테고리 정보도 함께 포함해서 서버로 전송한다: 프론트엔드
- [x] 포스트 작성 요청 API 시 태그와 카테고리 정보도 함께 저장한다: 백엔드

**Comment by sunhpark42** [comment]
브랜치 명 feature/category-tag

**Comment by gracefulBrown** [comment]
#114 에서 작업이 마무리 되었습니다~
