### ISSUE TITLE
역량 관리 기능을 구현한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#613]
## 기능 설명
- 역량을 관리한다.

## 체크 리스트
- [x] 기본 역량을 선택하여 초기화 할 수 있다.
- [x] 역량 목록을 조회할 수 있다.
- [x] 새로운 역량을 추가할 수 있다.
- [x] 자식 역량을 추가할 수 있다.
  - [x] 존재하는 이름이나 색상으로 역량을 추가 할 수 없다.
- [x] 역량 정보를 수정할 수 있다.
  - [x] 존재하는 이름이나 색상으로 역량을 수정 할 수 없다.
- [x] 역량을 삭제할 수 있다.
  - [x] 자식 역량이 있는 경우 부모 역량을 삭제할 수 없다.

## 참고
https://github.com/woowacourse/prolog/discussions/610

**Comment by gracefulBrown** [comment]
## 12월 15일
- [ ] 역량 이력 UI 결정
- [ ] 역량 이력 API 논의

## 시나리오
- 사용자가 백엔드 & 프론트엔드& 제 3자의 길을 선택하게 한다.
- 서버에서 백엔드나 프론트엔드를 선택하면 기본 역량을 가져온다.
- 역량 페이지 하단에는 취소, 저장 버튼이 있다.
- 저장 버튼을 선택하면 역량 이력이 저장이 된다. (역량 저장 API 필요)
  - 한꺼번에 역량을 저장하는 API가 필요할 것 같음
- 역량을 업데이트하면, 저장버튼을 눌렀을 때 역량 이력이 추가된다.
  - 현재 상위역량등록, 하위역량등록 / 수정 / 삭제가 나뉘어 있음
  - 수정이나 삭제를 눌렀을 때, 변경된 것이 없는 것을 프론트에서 체크? 백엔드에서 체크?
  - 백엔드에서도 변경된 것이 없을 때 이를 알려주는 에러코드가 필요할 것 같음.
- 역량 이력을 선택하면, 이전의 역량 이력을 보여준다.

**Comment by gracefulBrown** [comment]
# API

역량을 저장
PUT /abilities

역량을 조회: 가장 최근의 역량 이력
GET /abilities

역량 목록
GET /abilities-history

**Comment by gracefulBrown** [comment]
- 역량 이력 기능은 후순위로 밀림
- 역량을 생성하고 제거하고 수정할 수 있는 관리 기능을 구현하는 것으로 목표가 변경됨

**Comment by gracefulBrown** [comment]
## 역량 추가 시 요청이 오지 발생하지 않음
- 역량 추가하기 > 저장을 눌러도 POST 요청이 발생하지 않음
![image](https://user-images.githubusercontent.com/46308949/158683640-a9773ce3-ebe2-4be4-b2e4-8556effce880.png)

![image](https://user-images.githubusercontent.com/46308949/158683765-7e1032fb-7ca7-4620-83ef-1eadd9ce8464.png)

**Comment by devhyun637** [comment]
브라운 저거 확인해봤는데, 역량 이력을 받을 때 isParent로 오던 값이 parent로 오고있어서 문제가 있는 것 같아요!

post는 저는 제대로 동작하고 있습니다

**Comment by devhyun637** [comment]
브라운 혹시 어디를 수정한것일까효..?
1. API 응답 결과
2. 예시 응답 결과 (이건 제가 수정해야하는 것)

요청
GET **/members/${username}/abilities**

```
HTTP/1.1 200 OK
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json
Transfer-Encoding: chunked
Date: Mon, 18 Oct 2021 16:50:06 GMT
Keep-Alive: timeout=60
Connection: keep-alive
Content-Length: 942

[ {
  "id" : 1,
  "name" : "상위 역량 이름1",
  "description" : "상위 역량 설명1",
  "color" : "#001122",
  "isParent" : true,
  "children" : [ {
    "id" : 3,
    "name" : "하위 역량 이름1",
    "description" : "하위 역량 설명1",
    "color" : "#001122",
    "isParent" : false
  } ]
}, {
  "id" : 2,
  "name" : "상위 역량 이름2",
  "description" : "상위 역량 설명2",
  "color" : "#ffffff",
  "isParent" : true,
  "children" : [ {
    "id" : 4,
    "name" : "하위 역량 이름2",
    "description" : "하위 역량 설명2",
    "color" : "#ffffff",
    "isParent" : false
  } ]
}]
```

현재 오는 응답값
```
[{
      id: 69,
      name: '1111',
      description: '',
      color: '#000000',
      parent: true,
      children: [],
}]
```

**Comment by gracefulBrown** [comment]
@devhyun637 자식 역량응답만 적용해두었네요;;
다시 확인 부탁해요~

**Comment by devhyun637** [comment]
브라운 이거 적용이 안된거같은데 한번만 더 확인해주실 수 있나요?ㅠㅠ

그리고 기본역량 들고오는게 안되는거 같은데
**기본 역량 조회** `GET /abilities/templates/{be or fe}` 도 한번만 확인해주세요!

++
기본 역량 조회에서 Post 인지 Get인지 모르겠습니다!(기본역량을 가져오는 동시에 바로 저장이 되어야하긴 합니다)

**Comment by gracefulBrown** [comment]
@devhyun637 
`POST /abilities/templates/{be or fe}` 로 요청주시면 됩니다!
요청하고 바로 역량 목록 조회도 같이 호출해주세요~

**Comment by devhyun637** [comment]
왜.. 404가 뜰까효..?
그리고 PR에 conflict 나는 것 같아요!

<img width="716" alt="스크린샷 2022-03-19 오후 5 17 38" src="https://user-images.githubusercontent.com/59258239/159113503-a5b967c4-6947-46f4-9fd7-d0bee03b4ccc.png">

**Comment by gracefulBrown** [comment]
@devhyun637 
templates -> template 였네요;;

**Comment by devhyun637** [comment]
학습로그에 역량을 매핑하는 작업을 진행중인데 궁금한 사항이 있습니다.

1. [역량이 포함된 학습로그 조회](https://github.com/woowacourse/prolog/issues/723)는 역량을 등록하지 않은 경우에는 빈 배열값으로 오는 걸까요..? 저는 역량이 등록되어 있지 않은 경우에는 abilities가 빈배열로 올 것이라고 생각했는데, 현재 어떠한 학습로그에도 역량이 매핑되어 있지 않은 경우에는 응답이 빈배열로 오는 것 같습니다. (만약, 제가 생각한 방법이 맞다면 페이지네이션 정보가 추가되어야 할 것 같습니다.)

2. 학습로그에 역량 맵핑을 작업중인인데 500대 에러가 뜨는 이유가 무엇일까효..?
<img width="591" alt="스크린샷 2022-03-19 오후 10 28 44" src="https://user-images.githubusercontent.com/59258239/159123072-f78d542e-78ba-44ff-8207-64b0e184c835.png">
<img width="705" alt="스크린샷 2022-03-19 오후 10 29 25" src="https://user-images.githubusercontent.com/59258239/159123108-8761861f-39c4-44e3-a9ef-79d5f4645e25.png">

**Comment by gracefulBrown** [comment]
@devhyun637 아아 그 부분은 페이징 처리 때문에 논의 후 작업을 진행하려고 홀딩 상태입니다!
이 이슈는 역량 관리 이슈이므로 여기까지 진행하고 
학습로그 맵핑은 https://github.com/woowacourse/prolog/issues/614 이슈에서 진행하겠습니다!

**Comment by gracefulBrown** [comment]
@devhyun637 
현재 까지 작업된 부분 pr요청 부탁드립니다! 요청 주시면 바로 머지 후 새 브랜치 열어서 #614 진행하시죠~

**Comment by gracefulBrown** [comment]
@devhyun637 
DELETE /abilities 요청 시 `Authorization` 헤더의 값이 `Bearer null` 로 넘어오고 있습니다!
![image](https://user-images.githubusercontent.com/46308949/159145824-8a4fcbcd-e105-4015-a5f4-5d04921917a9.png)
