### ISSUE TITLE
역량과 학습로그를 맵핑한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#614]
## 요구 사항
- [x] 역량 페이지 > 학습로그 목록 조회 (맵핑된 역량도 함께 노출)
- [x] 학습로그 목록에 역량 부분을 클릭하여 맵핑된 역량 설정 변경하기
- [x] 역량별 학습로그 (역량 필터)

### 역량이 맵핑된 학습로그 조회
- 매핑된 역량 표현 방법: 한줄로 보여주되 많아지면 두줄 세줄로 늘어나도록 구현
  - 맵핑된 역량이 많을 경우 항목 별로 높이가 달라질 수 있지만 복수개의 역량이 맵핑될 가능성이 낮다고 판단(~작업의 빠른 진행을 위해~)
  - 추후 더 나은 UI가 있는 경우 개선 가능
<img width="948" alt="image" src="https://user-images.githubusercontent.com/46308949/159288141-a027b3d1-8326-46ed-a753-bb1bc2389a1b.png">

### 맵핑 역량 관리
- ... 버튼을 누르면 역량 목록 팝업이 노출
- 이미 선택된 역량은 체크 표시, 이 상태에서 다시 누르면 맵핑이 해제됨
- 선택되지 않은 역량을 누르면 맵핑 추가
- 역량 선택 정책
  - 역량은 기본적으로 자식역량을 선택하는 것을 권장
  - 자식 역량에서 선택할 역량이 없는 경우 부모 역량을 선택할 수는 있음
  - 부모 역량과 그 부모 역량의 자식 역량을 선택하는 경우는 어색한 상황이라고 볼 수 있음
    - (논의 필요) 부모 역량이 선택된 상태에서 해당 부모의 자식 역량을 선택한 경우 선택했던 부모 역량은 선택이 해제됨
    - (논의 필요) 자식 역량이 선택된 상태에서 부모 역량을 선택하는 경우 선택했던 모든 자식 역량의 선택이 해제됨

![image](https://user-images.githubusercontent.com/46308949/159288523-da364bda-56ed-4d80-92db-6ff4dc65f0df.png)

### 역량별 학습로그 목록 필터링
- 상단 역량 관리 영역에서 특정 역량을 누르거나 하단 학습로그 목록에서 역량을 누를 경우 필터링
- x를 누르면 선택된 역량이 해제됨

<img width="949" alt="image" src="https://user-images.githubusercontent.com/46308949/159290883-1438bb64-19f8-4755-a62f-1c68f56b8562.png">

## 기존 스펙 & 화면에서 변경되는 부분
- 학습로그를 불러오는 과정이 없어짐
  - 역량별 학습로그 등록하기 팝업 제거
  - [삭제], [학습로그 불러오기] 버튼 제거
  - 체크박스 제거

![image](https://user-images.githubusercontent.com/46308949/144525720-07ee197e-67e7-48af-aa8a-48fd85282ddd.png)
![image](https://user-images.githubusercontent.com/46308949/144525789-99042d62-a9d8-43d3-8926-3fdb50e5f55d.png)

## 참고
https://github.com/woowacourse/prolog/discussions/610

**Comment by gracefulBrown** [comment]
# API 종류
- 저장
- 조회

# 역량 초기화 API

# 저장 API
```
{
  abilities: [
    {
      // ability
    }
  ]
  studylogs: [
    {
      // studylog
    }
  ]
}
```

**Comment by devhyun637** [comment]
** 해야하는 일

- 현재 API 요청하는 부분이 전부 500에러가 뜨고 있습니다. TODO 부분으로 프론트 부분은 살펴보아야하는 코드를 표시했습니다. 보다가 이해가 안가는 부분이 있으면 저에게 DM주세요 :)
- API 연동을 하지 못해서 백엔드에서 정보를 받아서 뿌려주는 부분을 못하고 있습니다. 이부분이 되어야 API 명세서를 좀 더 디벨롭할 수 있을 것 같습니다(아마 수정되어야하는 부분 있을거 같습니다)
- 자식 역량 추가/삭제/수정
- 학습로그 이력페이지 목록 가져오기(영상에서 히스토리 누르면 나오는 부분)
- 학습로그 역량 이력을 선택하면 이력페이지에서 해당 히스토리를 보여주는 것

**Comment by gracefulBrown** [comment]
## 학습로그에 역량 맵핑
### request
```
Request method:	PUT
Request URI:	http://localhost:4000/studylogs/1/abilities
Headers:		Accept=*/*
				Content-Type=application/json; charset=UTF-8
Body:
{
    "abilities": [
        1
    ]
}
```

### reponse
```
HTTP/1.1 200 
Content-Type: application/json

[
    {
        "id": 1,
        "name": "프로그래밍",
        "description": "프로그래밍 관련입니다.",
        "color": "red",
        "parent": true,
        "children": [
            {
                "id": 2,
                "name": "언어",
                "description": null,
                "color": "red",
                "isParent": false
            }
        ]
    }
]
```

## 역량이 포함된 학습로그 조회
### request
```
Request method:	GET
Request URI:	http://localhost:4000/members/gracefulBrown/abilityStudylogs
```

### reponse
```
HTTP/1.1 200 
Content-Type: application/json

[
    {
        "studylog": {
            "id": 1,
            "author": {
                "id": 1,
                "username": "gracefulBrown",
                "nickname": "브라운",
                "role": "CREW",
                "imageUrl": "https://avatars.githubusercontent.com/u/46308949?v=4"
            },
            "createdAt": "2022-03-11T09:51:09.397",
            "updatedAt": "2022-03-11T09:51:09.397",
            "mission": {
                "id": 1,
                "name": "backend 지하철 3차 미션",
                "level": {
                    "id": 1,
                    "name": "레벨1"
                }
            },
            "title": "새로운 스터디로그",
            "content": "content",
            "tags": [
                
            ],
            "scrap": false,
            "read": false,
            "viewCount": 0,
            "liked": false,
            "likesCount": 0
        },
        "abilities": [
            {
                "id": 1,
                "name": "프로그래밍",
                "description": "프로그래밍 관련입니다.",
                "color": "red",
                "parent": true,
                "children": [
                    {
                        "id": 2,
                        "name": "언어",
                        "description": null,
                        "color": "red",
                        "isParent": false
                    }
                ]
            },
            {
                "id": 4,
                "name": "TDD",
                "description": null,
                "color": "blue",
                "parent": false,
                "children": [
                    
                ]
            }
        ]
    }
]

```
