### ISSUE TITLE
그라파나를 적용한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#618]
- [x] 모니터링 개선을 위해 그라파나를 적용한다.
- [x] #631
- [x] #632

**Comment by qhals321** [comment]
2021-12-06
## 회의 일지

- 참고할만한 자료
    - [https://meetup.toast.com/posts/237](https://meetup.toast.com/posts/237)
    - [https://roasted-darkness-ef2.notion.site/a7bee7f84fd142a5a9b83491fba067eb](https://www.notion.so/a7bee7f84fd142a5a9b83491fba067eb)

### 도입 이유

- 클라우드 와치의 단점
    - 실시간성 부족 (예시 : 부하테스트 진행 시 시스템 자원이 바로 보이지 않아 즉각적인 피드백을 받기가 힘듬)
    - 권한이 없는 탓에 로그 스태시 활용이 힘듬 (로그로 수치화 테이블 작성이 힘듬)
    - 로그인 과정과 시각화 테이블을 틀어놓는 과정이 너무나 번거로움

### 최종 목표

- 필요한 자원을 손쉽게 모니터링이 가능하게 한다.
- 로그를 출력 가능하게 한다.
- 로그인 과정이 간편하게 한다. (**아이디 + 비밀번호** or [ip 제한 ⇒ 번거롭다(카페나 움직이면서 코딩하면 확인이 불가)])

**Comment by qhals321** [comment]
진행 내용 문서화 작업.
https://github.com/woowacourse/prolog/wiki/Prometheus-%EC%99%80-Grafana-%EC%A0%81%EC%9A%A9%EA%B8%B0

**Comment by qhals321** [comment]
모니터링 작업 완료.
로그 작업 진행

**Comment by gracefulBrown** [comment]
남은 체크리스트는 별도 이슈로 분리하고 클로즈 하겠습니다

**Comment by gracefulBrown** [comment]
http://prolog.kro.kr/d/kJqrhgLnk/prolog-dev-log?orgId=1&from=now-24h&to=now
해당 url 은 데브 서버 로그 확인 주소입니다.
id : admin
pw : dksTmsl123!@#
