### ISSUE TITLE
에디터 적용(이미지 삽입 기능)

### ISSUE THREAD

**Issue by dudtjr913** [woowacourse/prolog#62]
이미지를 삽입할 수 있다.

**Comment by sihyung92** [comment]
[이미지 삽입기능 백엔드]
구현해야할 기능 목록
- 이미지 삽입 기능
  - S3 인프라 설정 및 IAM 권한 확인
  - 이미지를 폼데이터로 입력 받아 URL String을 반환하는 API 생성
    - [API] POST /image
    - Documentation 작성 
    - [예외] 이미지가 적절한 형식의 확장자가 아니면 예외
    - [예외] 이미지가 null인 경우 예외

**Comment by JUDONGHYEOK** [comment]
## 1주차(09/13~09/18)

구상하기

### 백엔드
- S3인스턴스 생성 및 사용법 익히기

### 프론트엔드
- 이전 브랜치 분석 및 URL 길이 수정 방법 탐구

## 2주차(09/19~09/26)

최종 구현
### 백엔드
- 이미지 파일 받아서 URL반환하는 API 생성

### 프론트엔드
- 이미지 올리는 이벤트 캐치 후 이미지 파일 전송 및 URL 처리
