### ISSUE TITLE
[bug] 글 생성, 수정 및 삭제가 안되는 이슈

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse/prolog#628]
현재  [https://dev.prolog.techcourse.co.kr/](https://dev.prolog.techcourse.co.kr/) 

테스트 환경: 구글 크롬

재현 방법 : dev 서버에서 로그인 후 글 작성, 수정, 삭제를 시도한다.

![](https://user-images.githubusercontent.com/67677561/146094687-a581ffdc-36d3-48cf-885a-2d2b31f7b917.png)

![](https://user-images.githubusercontent.com/67677561/146094713-c171c995-8aaf-499d-bd8c-2e638ba41e1f.png)

**Comment by seovalue** [comment]
dev beanstalk public ip 변경되어 보안그룹에 추가되어있지 않아 발생한 문제였습니다!
해결하여 close 합니당 :)
