### ISSUE TITLE
스크랩+읽음처리 후 studylog 삭제가 안되는 문제

### ISSUE THREAD

**Issue by xrabcde** [woowacourse/prolog#634]
![image](https://user-images.githubusercontent.com/56033755/147917654-7bf743c2-7367-4a14-a0b7-e14ff4ce1275.png)

![image](https://user-images.githubusercontent.com/56033755/147917757-78dd6304-5509-4eb2-b54f-cad5fe6e8c4c.png)

- studylog 삭제 시 해당 studylog에 대한 scrap과 read가 같이 삭제되지 않아 발생하는 것으로 추정중
- 사용자 리액션 기능 구현 PR이 전부 머지된 이후에 브랜치 따서 작업시작하겠습니다

**Comment by Hyeon9mak** [comment]
아아악!
