### ISSUE TITLE
조회수가 2씩 증가한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#639]

**Comment by DWL5** [comment]
![image](https://user-images.githubusercontent.com/18106839/148077507-3ef26b55-8ab0-47c4-bc52-b733b6a2ade7.png)

이슈 확인해보았습니다.
실제로 동작 시 조회수가 2씩 증가함을 확인했습니다.

포스트 맨으로 request를 보내고, response를 검사했습니다. 
response는 8로 보내지는데, ui가 2배인 16으로 나타남을 확인했습니다.

**Comment by DWL5** [comment]
![image](https://user-images.githubusercontent.com/18106839/148078361-05810b7f-9d58-47cb-a0c8-c0337ce4b754.png)

직접 로컬에서 돌려본 결과 조회수 2씩 증가되는 것 확인했습니다~
request를 두번 보내고 있는 것 같습니다.
포스트맨으로도 테스트 시 1씩 증가하는 것 확인했습니다!
