### ISSUE TITLE
통합 로그인을 구성한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#640]
- [ ] IDP 구축
- [ ] No Security 서비스 샘플
- [ ] YES Security 서비스 샘플

**Comment by gracefulBrown** [comment]
# IDP 클라이언트
- 인증 로직을 직접 구현한 클라이언트도 붙을 수 있어야 함
- 시큐리티 클라이언트도 붙을 수 있어야 함

**Comment by pkeugine** [comment]
prolog-idp 레포지토리에도 이슈로 남겨놓겠습니다.

**Comment by gracefulBrown** [comment]
prolog-idp 작업 진행 상황을 고려한 후 이슈 재생성하겠습니다.
