### ISSUE TITLE
[메인페이지] 메인페이지를 개편한다.

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse/prolog#647]
### 메인페이지 컨텐츠
1. 상단배너
2. 인기있는 검색어
3. 인기있는 학습로그
4. 최신 학습로그
5. 명예의 전당

* 참고 : https://github.com/woowacourse/prolog/discussions/626
* UI : https://www.figma.com/proto/15qD4XpMvnbBNDMJbzCjLn/Untitled?node-id=2%3A3&scaling=scale-down&page-id=0%3A1

### 네비게이션
* 홈, 학습로그, 검색 네비게이션으로 변경
* 학습로그 검색 창은 검색 화면으로 변경 혹은 검색아이콘으로 변경하여 눌렀을 시 드롭박스 형식으로 검색가능하도록 변경
* 학습로그 목록 페이지 분리

### 일정
* API 명세 및 단계별 메인페이지 개편: (회의 예정)

**Comment by sunhpark42** [comment]
## 논의 내용

1.  상단배너는 현재는 서버에 배너를 저장할 필요가 없어보임 => 우선순위 ▼
2.  **검색어 (New)**
    1.  검색 횟수로 판단해야 할 것 같음. 
    2.  검색 파트와 협의 필요할 것 같다.
    3.  @gracefulBrown  논의 필요
    4.  엘서에서 뽑아낼 수 있다.
        1.  엘서 통계 방법 알아보고 @Hyeon9mak 이 진행.
        2.  시간이 오래 걸릴 것 같으면 담당자 찾아보기.
    5.  **호출하면 호출시점으로부터 -7일까지 검색하기**
    6.  **매주 월요일 13시 업데이트(브라운이 누르기)**
    7.  **2단계 - 슬랙봇으로 하기**
3.  최신 학습로그 => 현재도 있음.
4.  **인기있는 학습로그 (New)**
    1.   조회수, 좋아요, 스크랩 수가 판단 조건이 될 것 같음
        1.  조회수 \* 1 + 좋아요 \* 3 + 스크랩 \* 3 이런식으로
        2.  현재 스크랩 수 수집 안함.
        3.  **조회수 \* 1 + 좋아요 \* 3 으로 판단.**
        4.  추후에 실제로 띄워놓고 값 조정하기.
    2.  각각의 점수 비중 판단하는게 좋을 듯
    3.  날짜도 필터링 조건으로 작동해야 할 것 같다. (2년전 글이 항상 상단에 존재 할 수 있는 가능성 있음)
    4.  주간 업데이트, 해당 기간에 조회된, 좋아요, 스크랩 수만 계산하기.
    5.  level5쯤 사용량이 줄어들 때, 조회수가 0 면 어떻게 할 지?
        1.  특정 주간에 이벤트가 없으면, 해당 영역을 삭제(노출 x)
        2.  해당 조회 기간을 늘리기 ( -7 + (-7) + (-7) ...)
        3.  기간 자체를 30일 60일 이런식으로 조회 기간을 늘려버리기
        4.  갱신이 안되면 이전 주차 거 그대로 보여줌.
    6.  **호출하면 호출시점으로부터 -7일까지 검색하기. (배치 구축은 아직 어려울듯)**
    7.  **추후 배치를 구축해서 주간/월간 업데이트를 하는 식으로 변경**
    8.  **매주 월요일 13시 업데이트(브라운이 누르기)**
    9.  **2단계 - 슬랙봇으로 하기**
5.   **명예의 전당 (New)**
    1.  프론트 / 백엔드 구분해야함
    2.  회원 정보에서 정보 추출
    3.  레벨별 결산 _(무슨 테마로 할 지 결정 필요)_
        1.  학습로그를 가장 많이 작성한 크루
        2.  좋아요를 가장 많이 받은 크루
        3.  좋아요를 가장 많이 누른 크루
        4.  스크랩을 가장 많이 한 크루
    4.  **컨텐츠 소비자 1명, 컨텐츠 생산자 1명으로 각 분야 뽑기 총 4명.**
    5.  우수회원(ㅋㅋㅋ) 선정 기준을 노출 시키지 않기 x - 어뷰징 생길 수 있음.
    6.  **글에 미친 웨지 이런느낌으로 선정기준을 노출 시켜도 좋을 것 같아요.**
    7.  **컨텐츠 소비왕!**
    8.  **이달의 MVP! 라고 써두고 `레벨1 가장 많은 컨텐츠를 소비한 크루` 처럼 작게 남기기.**
    9.  path 동일하게 두고, query 를 바꿔 날리기 

## 우선 순위

1.  인기있는 학습로그
2.  검색어
3.  명예의 전당 (레벨 1 끝나기 전까지 구현되면 됨)

*   **프론트 Only 인 부분**
    *   최신학습로그
    *   배너 영역
    *   학습로그, 검색 페이지 분리

**Comment by sunhpark42** [comment]
1.  우선 인기있는 학습로그에 대한 API 구현만 이슈 잡아주세요.

**Comment by sunhpark42** [comment]
2022\. 02. 28 진행도

*   [ ] 인기있는 학습로그 **(PR)**
*   [ ] 검색어
*   [ ] 명예의 전당 (레벨 1 끝나기 전까지 구현되면 됨)
*   [x] 최신학습로그
*   [x] 배너 영역
*   [x] 학습로그, 검색 페이지 분리

**Comment by sunhpark42** [comment]
ES 이슈로 최근 검색어는 후순위

**Comment by sunhpark42** [comment]
@Hyeon9mak 현구막이 진행하는 인기 학습로그 조회 성능 개선 이후로 우선 홀딩하겠습니다~

**Comment by gracefulBrown** [comment]
## 일정
- 3월 14일 공유 
  - 조회용 / 갱신용 API 분리
