### ISSUE TITLE
로그인 후 이용 가능하다는 창이 나올 때 로그인으로 redirect 가 되었으면 좋겠습니다!

### ISSUE THREAD

**Issue by qhals321** [woowacourse/prolog#671]
다음과 같은 화면이 나올 때 확인을 누르면 바로 로그인으로 이동하는 편의 기능이 생겨도 좋을 것 같습니다!
![image](https://user-images.githubusercontent.com/63535027/150671286-422f3603-c910-48b2-964c-e72b84951358.png)

**Comment by sunhpark42** [comment]
현재 로그인 페이지가 없는데, 어떻게 구현하면 좋을까욤?

**Comment by gracefulBrown** [comment]
이 부분을 구현하기 위한 페이지를 만들면 가능할까요?

**Comment by sunhpark42** [comment]
페이지를 만들면 로그인 단계가 늘어나서 confirm을 이용해서 로그인하시겠습니까? 라고 떠도 좋을 것 같아욤

**Comment by airman5573** [comment]
글을 오랫동안 작성하다가 세션이 만료되서 해당 alert이 뜨고 로그인 페이지로 넘어가면, 작성한 글이 날라갈 위험이 있습니다.
자동 임시 저장기능이 구현되고 redirect기능이 추가되면 좋겠습니다.

**Comment by gracefulBrown** [comment]
#312 에서 진행하겠습니다.
