### ISSUE TITLE
로컬에서 flyway가 정상 동작하는지 확인하는 방법을 고민한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#672]
## 문제 상황
AS IS 
- flyway에 의존하지 않고 동작하기 때문에 flyway 정상 동작 확인은 dev 배포 시도 이후에 가능함

TO BE
- local에서도 flyway를 동작시켜 확인할 수 있도록 함

## 진행 내용
- [ ] local 배포에 사용하는 profile을 하나 더 추가한다.
  - docker를 이용하여 mysql과 es를 띄울 수 있도록 구성한다.

**Comment by wilgur513** [comment]
### 일정 계획
* [ ] **9/8 ~ 9/14** :  문제 해결을 위해 필요한 부분까지 flyway 및 docker(mysql, es) 사용법 학습
* [ ] **9/14 ~ 9/19** : docker를 이용해 mysql, es 구성
