### ISSUE TITLE
반응형 UI 를 적용한다.

### ISSUE THREAD

**Issue by sunhpark42** [woowacourse/prolog#686]
모바일 max-width 420px 만 우선 적용

- [ ] 메인페이지 **(PR)**
- [ ] 학습로그 목록 페이지 **(PR)**
- [ ] 학습로그 단건 조회 페이지 **(PR)**
- [x] #851
- [x] #853
- [x] #852
- [x] #854
- [x] #855

**Comment by gracefulBrown** [comment]
우선순위 조정으로 이슈를 닫습니다.
