### ISSUE TITLE
어드민 초기 셋팅을 구축한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#709]
## mvp
- 멤버 관리
  - 목록조회, ~~생성~~, 수정, 삭제
- 세션 관리
  - 목록조회, 생성, 수정, 삭제
- 세션 별 미션 관리
  - 목록조회, 생성, 수정, 삭제
- 세션 별 멤버 관리
  - 세션을 수강중인 멤버(session_member) 관리

**Comment by gracefulBrown** [comment]
- react-admin 3월 14일 페이지 적용 까지

**Comment by Hyeon9mak** [comment]
@gracefulBrown 요거 진행해봐도 괜찮을까요?

**Comment by bperhaps** [comment]
-[] #937

**Comment by bperhaps** [comment]
@gracefulBrown 멤버관리의 생성은 어떤 기능인가요?

**Comment by gracefulBrown** [comment]
@bperhaps 잘못된 정보네요ㅎㅎ 지웠습니다

**Comment by al-bur** [comment]
# 0729 회의

## 회의 내용
- admin issue에 앨버, 코다 참여하기로 결정되었습니다.
- 리액트를 활용하여 가독성 있는 코드를 작성하는 게 필요합니다. (추후 백엔드 크루들이 직접 수정할 수 있도록, 추상화X)
- 1차적으로, session, mission 추가등 현재 수작업으로 하고 있는 작업들을 CRUD 할 수 있는 admin을 만들어볼 수 있습니다.


## 다음 일정
- 7월 30일 ~ 31일 사이에, 코다에게 해당 내용 전달
- 8월 1일에 admin 개발에 대하여 브라운과 회의 진행

**Comment by al-bur** [comment]
# sb Admin vs react-admin

- admin 페이지를 구현하는 데 위 두 가지 방법이 존재합니다. 
    1. sb Admin(또는 다른 UI 라이브러리) => UI 라이브러리로써 admin 페이지에 필요한 UI들을 제공해줍니다.
    2. react-admin => react로 만들어진 admin 라이브러리로써 UI+로직을 제공해줍니다.

# 장단점

**Comment by al-bur** [comment]
# 0808 정기 회의

- 수요일까지 어드민 초기 세팅
- 일요일까지 sessions, missions CRUD할 수 있도록 구현 및 배포

**Comment by al-bur** [comment]
# 0816 공유내용

[prolog-admin-repository](https://github.com/woowacourse/prolog-admin)

## 현재 진행상황

- [x] admin 초기 세팅 완료
- [x] missions CR 기능 구현 완료 (PR)

## 이번주 계획

- [ ] sessions 기능 구현 완료

## 레벨4 계획

- [ ] github auth 인증 도입 (해당 사항은 레벨3때까지 완성이 불가능할 것이라 예상되어 레벨4에 진행하기로 했습니다.)

**Comment by al-bur** [comment]
초기 세팅 완료
