### ISSUE TITLE
학습로그 에디터를 개선한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#711]
## 요구사항
- 학습로그 에디터를 소개글 에디터로 전환
- 미션 선택, 태그 등 정보 추가는 우측으로 이동 (아래 이미지 참고)

## 참고
![image](https://user-images.githubusercontent.com/46308949/156583051-226b0301-2440-429e-8002-0df99d344db2.png)

**Comment by sunhpark42** [comment]
### 시안1
<img width="982" alt="스크린샷 2022-03-05 오후 1 08 51" src="https://user-images.githubusercontent.com/67677561/156867080-6e170ace-99ff-456b-83be-d8bfb73925d3.png">
### 시안2
<img width="981" alt="스크린샷 2022-03-05 오후 1 09 01" src="https://user-images.githubusercontent.com/67677561/156867086-eedd9ae4-2d61-47f1-91db-74efee5a20f1.png">

**Comment by gracefulBrown** [comment]
시안 2 한표합니다.
요론 느낌으로?ㅎㅎ
<img width="815" alt="image" src="https://user-images.githubusercontent.com/46308949/156867276-0b1d1c98-0197-4bfc-b195-22004eb91995.png">

**Comment by gracefulBrown** [comment]
![image](https://user-images.githubusercontent.com/46308949/156870813-754ed26d-7dd0-4242-a453-3f90cd004372.png)

**Comment by gracefulBrown** [comment]
메시지 알림
> 뒤로가기 누르면 사이트를 벗어나면 내용이 저장되지 않을수도 있습니다. 임시저장 버튼을 눌러주세요

**Comment by gracefulBrown** [comment]
## 변경된 요구사항
- 학습로그 작성 시 세션을 추가할 수 있다.
- 학습로그 작성 시 미션을 추가할 수 있다.
- 세션과 미션을 필수값이 아니다.

## 추가 작업
- [ ] 학습로그 작성/수정 시 세션정보 추가로 받기
- [ ] `세션 - 학습로그` 정보와 `미션 - 학습로그`를 추가
- [ ] 기존 학습로그 테이블에 있던 미션 정보는 제거
