### ISSUE TITLE
서버에서 예외 발생시 예외처리 방법에 대해 논의한다

### ISSUE THREAD

**Issue by sihyung92** [woowacourse/prolog#73]
제안 : status code와 함께 body로 {"message" : "에러 내용"} 형식의 JSON을 반환한다.

**Comment by gracefulBrown** [comment]
다른 서비스의 예시를 찾아봐도 좋겠네요 :)
https://www.baeldung.com/rest-api-error-handling-best-practices

**Comment by gracefulBrown** [comment]
#101 에서 논의되었습니다
