### ISSUE TITLE
역량 관련 테스트 에러

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse/prolog#752]
![image](https://user-images.githubusercontent.com/37354145/159213343-0eeeff2d-d82a-46a9-b60f-5263f2910023.png)

2022년 3월 21일 15시 20분 기준 develop 브랜치
역량 관련 테스트 두 곳에서 에러가 발생합니다.

**Comment by gracefulBrown** [comment]
부모 역량과 자식 역량의 양방향 관계 제거 예정이라 테스트를 제거함
https://github.com/woowacourse/prolog/commit/06a948f3517ee3ee8bbb363ef26bb6366433912e
