### ISSUE TITLE
댓글 기능 구현을 검토한다.

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#788]
## 개요
- 학습로그에 대해 조금 더 깊은 이야기를 나눌 수 있는 댓글 기능을 제공한다.
- 프론트엔드 리소스가 부족 할 경우 인수 테스트 기반으로 백엔드 먼저 기능 구현을 고려할 수 있다.

## 작업 내용
- [x] 댓글 기능 요구사항 도출
- [x] 댓글 UI 도출
- [x] 작업 분량 측정

**Comment by da-nyee** [comment]
요거 하고 싶습니다 ~!

**Comment by gracefulBrown** [comment]
## MVP 
- 댓글은 학습로그처럼 마크다운으로 작성할 수 있다.
- 댓글이 N개 이상인 경우 더보기 버튼을 노출하여 부분적으로 노출한다.
- 댓글에서 보여져야하는 정보
  - 작성자
    - 썸네일
    - 닉네임
  - 작성일자
  - 내용

## 추가 사항
- 리액션: 리액션은 필요는 하지만 추후에 모듈화 한 뒤 리포트와 함께 댓글에 적용 예정
- 더보기/간략히보기 : 댓글 작성은 무한대로 가능하지만 3줄이 넘어가면 로 모든 내용을 볼 수 있게 한다.

**Comment by gracefulBrown** [comment]
# API
## 생성
- POST /studylogs/1/comments

**Comment by gracefulBrown** [comment]
UI 컨셉은 깃헙

**Comment by gracefulBrown** [comment]
1. ~작성창 제일 위에 두고 오래된 댓글을 보여주고~
2. 작성창을 제일 아래에 두고 최신 댓글을 보여주고 이전 댓글을 더보기

1~100이 있으면
desc, reverse=true, size 10, page 1
ex. 90~100 응답하고 load more하면 80~90 응답

**Comment by gracefulBrown** [comment]
## 일정
- 배포 일정 : 6월 중순 오픈
- 주간회의 때 진행 상황 공유

## 할 일
- [ ] UI 공유
- [ ] API 문서화 전달
