### ISSUE TITLE
블로그 글 목록을 관리한다

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#789]
# 해결하고자 하는 문제
- 크루들의 블로그 글을 모아볼 수 있다.
- 내 글을 다른 크루들에게 공유하고 싶다.

# 해결 방법

## 블로그 글 수집
- 초기에는 사용자가 직접 자신의 글을 링크로 등록하게 하기
- 나중에는 rss 구독을 통해 자신의 블로그를 등록해두면 자동으로 프롤로그에 등록 되도록 하기

## 블로그 글 목록 노출
- 학습로그 목록 처럼 블로그글 목록 페이지를 만든다.
- 등록 순으로 블로그 카드를 목록으로 보여준다.
- 카드를 클릭할 경우 해당 블로그로 이동이 된다.
- 카드는 og tag에서 제공되는 정보로 구성된다.

**Comment by seokhongkim** [comment]
아티클 티켓과 중복되어 종료합니다.
