### ISSUE TITLE
웹 페이지 하단에 빈 공간 추가

### ISSUE THREAD

**Issue by Yboyu0u** [woowacourse/prolog#798]
- 웹 페이지 하단에 빈 공간이 전혀 없어서 답답한 느낌이 드네요. 
![image](https://user-images.githubusercontent.com/63579113/165036074-11905339-fe0a-42f1-8f70-70b7a4a32693.png)

**Comment by sunhpark42** [comment]
이부분은 이번에 에디터 개선 작업과 함께 추가될 예정입니다. 원래 공간이 있었는데, 중간에 코드가 꼬인 것으로 보입니다.

**Comment by gracefulBrown** [comment]
해당 이슈는 해결되어 close 하겠습니다.
