### ISSUE TITLE
학습로그 작성 기능

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#8]
# 학습로그 작성
- 승인된 멤버는 학습한 내용의 기록을 위해 학습로그를 작성한다.🌟

## 정상 케이스
- when: 학습로그를 작성한다.
- then: 학습로그 목록에 추가된다.

## 항목 중 빠진게 있는 케이스
- given: 작성자 or 제목 or 본문이 작성되지 않음
- when: 학습로그를 작성한다.
- then: 작성 실패 후 에러메시지를 보여준다.

## 글 작성 중 뒤로 가는 케이스
- given: 작성자 or 제목 or 본문이 작성된다.
- when: 학습로그를 작성하기 전 뒤로가기를 한다.
- then: 에러메시지를 보여준다.

**Comment by sihyung92** [comment]
### [210513][백엔드][웨지포모] 학습로그 작성,전체보기 
- 인텔리제이 개발환경 구성 및 기능요구사항 작성
- 논의해볼 사항 : 
    1. 제목의 글자 수 제한
    2. API URL, request, response

**Comment by sihyung92** [comment]
[210516][백엔드][웨지포모] 하드코딩된 값을 반환하는 API 작성
- 컨트롤러 단위테스트 작성 및 API작성
- 노션 최신화 및 작성 결과 슬랙에 공유
