### ISSUE TITLE
학습로그에 역량이 추가 되지 않는 버그 수정

### ISSUE THREAD

**Issue by JUDONGHYEOK** [woowacourse/prolog#810]
프롤로그 역량 - 학습로그에 역량 매핑하기
학습로그에 + 버튼을 누르고 , 역량을 선택한 후 역량 등록을 누른 뒤 다시 + 버튼을 누르면 초기화되는 오류 -> 이전 등록 역량이 기억되어 있으면 좋을 것 같다.
![image](https://user-images.githubusercontent.com/65863017/165556304-517dadb6-dbcb-4dc8-bd47-bcce50e3e44f.png)

**Comment by 2yujeong** [comment]
#951
