### ISSUE TITLE
해시태그 하나를 먼저 작성하고 그 뒤에 새로운 태그 등록시 해시가 2개 되는 현상 개선 

### ISSUE THREAD

**Issue by euijinkk** [woowacourse/prolog#814]
- 현재상황
  새로운 태그를 등록할 때 해시태그를 먼저 입력하고 단어를 입력하면 단어 앞에 해시태그가 두 개가 되는 현상이 발생합니다.

  기존 태그를 등록할 때와 새로운 태그를 등록할 때의 동작이 다름

  새로운 태그를 등록할 때는 자동적으로 단어 앞에 하나의 '#'가 추가로 붙어서 이러한 현상이 발생하는 거 같습니다.

  이 경우 태그로 등록할 단어의 앞에 '#'이 추가로 붙은 채로 태그 등록이 되어서 내 프로필에서 태그를 확인할 때도 앞에 해시태그가 두 개 붙은 상태로 나타납니다.
- 개선 후 기대상황
  해쉬 # 이 하나만 생겨야 합니다.
- 화면 이미지
<img width="294" alt="image" src="https://user-images.githubusercontent.com/24906022/165557924-85afa41e-0e71-4692-8a73-ddc824a1795f.png">

**Comment by sunhpark42** [comment]
에디터 개선시에 함께 개선 된 사항입니다. [dev](https://dev.prolog.techcourse.co.kr) 환경에서 재 확인 부탁드립니다.
