### ISSUE TITLE
분야/레벨/미션 카테고리 세분화

### ISSUE THREAD

**Issue by kwannee** [woowacourse/prolog#824]
### 관련 영역
![164965086-fc8967a3-b93e-4a54-87d5-23cc4009edd3](https://user-images.githubusercontent.com/41886825/165575295-18709624-72a9-4172-a5c5-0c35cb24c836.png)

### 내용
글쓰기를 할 때 카테고리 선택시 스크롤을 내려가며 일일이 찾아 주어야 하는데, 분야/레벨/미션 별로 카테고리를 세분화하여 선택할 수 있으면 좋겠습니다!

### 추가 정보
[버그 및 개선 사항 취합하기, 이스트 1번](https://github.com/woowacourse/prolog/discussions/782)

**Comment by sunhpark42** [comment]
해당 건은 에디터 개선과 함께 개선 된 부분입니다. 참고바랍니다.
<img width="1205" alt="스크린샷 2022-04-29 오전 9 31 38" src="https://user-images.githubusercontent.com/67677561/165868453-7e3f5849-df67-47fb-a12e-185ca18d642c.png">
