### ISSUE TITLE
글 수정 영역을 viewport 전체 높이로 확대

### ISSUE THREAD

**Issue by JUDONGHYEOK** [woowacourse/prolog#825]
글 수정 시, 수정 영역이 너무 작은 것 같아요. 수정 영역을 viewport 전체 높이로 확대할 것을 제안합니다
<img width="1453" alt="스크린샷 2022-04-28 오전 12 40 06" src="https://user-images.githubusercontent.com/65863017/165557610-7cd8f162-c8d4-4a8e-9215-563ee0c00750.png">

**Comment by sunhpark42** [comment]
에디터 개선건과 함께 작업된 부분입니다. **[dev](https://dev.prolog.techcourse.co.kr/)** 환경에서 확인바랍니다.
