### ISSUE TITLE
글 작성 > 미션 선택 시 키보드 이벤트 적용

### ISSUE THREAD

**Issue by kwannee** [woowacourse/prolog#826]
### 관련 영역
![image](https://user-images.githubusercontent.com/41886825/165573730-f8445a7b-64da-4d19-aed2-a810c11c019e.png)

### 내용
글 작성 시, 미션 선택에서는 KeyBoard Event (ArrowUp, ArrowDown)가 동작하지 않음.

### 추가 정보
[버그 및 개선 사항 취합하기, 시지프 9번](https://github.com/woowacourse/prolog/discussions/782#discussioncomment-2624142)

**Comment by sunhpark42** [comment]
에디터 개선건과 함께 진행되었습니다. 확인바랍니다.
