### ISSUE TITLE
프로필 역량 페이지에서 추가, 수정, 삭제 버튼이 한 줄에 표시되도록 UI 개선

### ISSUE THREAD

**Issue by wonsss** [woowacourse/prolog#827]
## 현재상황 
- 프로필 역량 페이지에서 추가, 수정, 삭제 버튼이 한 줄에 표시되지 않고, 삭제 버튼이 아래줄로 내려간다.
## 개선 후 기대상황
- 프로필 역량 페이지에서 추가, 수정, 삭제 버튼이 한 줄에 표시되도록 한다.
## 이슈 생성 원인
-  감싸는 컨테이너 너비 문제일 것으로 추정
## 화면 이미지
![image](https://user-images.githubusercontent.com/59413128/165552893-c82b204d-55cb-4e48-83c8-f3a167327514.png)

**Comment by euijinkk** [comment]
[링크](https://github.com/woowacourse/prolog/issues/818) 와 같은 내용이므로 close 합니다.
