### ISSUE TITLE
카드의 너비를 전체 영역으로 설정

### ISSUE THREAD

**Issue by kwannee** [woowacourse/prolog#830]
### 관련 영역
<img width="1096" alt="164675082-001f0d3a-6c41-495b-907c-8989b8708a4f" src="https://user-images.githubusercontent.com/41886825/165571000-eb27055c-e29d-4fe6-a244-3043112985ed.png">

### 내용
메인화면 카드 슬라이더의 오른쪽에 다음 카드가 살짝 보이는데, 의도한 걸까요? 의도하지 않았다면 현재 보는 카드의 너비를 전체 영역으로 설정하는 것이 더 깔끔해보일 수도 있을 것 같아요.

### 추가 정보
[버그 및 개선 사항 취합하기](https://github.com/woowacourse/prolog/discussions/782#discussioncomment-2614541)

**Comment by sunhpark42** [comment]
이 부분은 사용성 상 횡스크롤이 되어야 해서 **사용자에게 횡스크롤임을 알릴 수 있도록** 의도한 부분입니다. 전체영역으로 설정하면 사용자 입장에서는 옆으로 슬라이드 되는지를 모를 수도 있어서요. 보기에 어색해보인다면 다른 방법으로 횡스크롤이라는 걸 사용자가 인지할 수 있는 방법을 고민해주시면 좋을 것 같습니다~

**Comment by JUDONGHYEOK** [comment]
추후 리써치 후 다시 고려함.
