### ISSUE TITLE
헤더에서 홈 버튼 제거

### ISSUE THREAD

**Issue by wilgur513** [woowacourse/prolog#836]
### 현재 상황
* 홈으로 이동하기 위해 PROLOG 로고와 헤더의 홈 버튼 사용
### 개선 사항
* PROLOG 로고와 헤더의 홈 버튼이 동일한 기능을 하므로 홈 버튼 제거

**Comment by euijinkk** [comment]
추후 논의후 결정하겠습니다

**Comment by al-bur** [comment]
홈 버튼이 현재 페이지가 어디인지를 나타내는 인디케이터 역할을 하고있어서 현황을 유지하기로 결정했습니다
