### ISSUE TITLE
Card hover 시 가시성 향상을 위해 UI 개선

### ISSUE THREAD

**Issue by her0807** [woowacourse/prolog#838]
## 현재 상황
메인 화면 인기있는 학습 로그 카드에 마우스를 올리면, (hover)
학습 로그 제목 색상이 변경되는데, 색이 눈에 띄지 않아 오히려 가시성이 떨어진다.
<img width="725" alt="스크린샷 2022-04-25 오후 4 01 47" src="https://user-images.githubusercontent.com/26570275/165037017-fa8e8752-afc8-4280-9155-4b7ee4967b02.png">

## 개선 내용
hover 시 변경되는 색깔을 조금 더 어두운 색으로 변경한다.

## 기대상황 
가시성이 올라간다.

## 참고
- https://github.com/woowacourse/prolog/discussions/782#discussioncomment-2614544

**Comment by sunhpark42** [comment]
해당 이슈 antd 라이브러리 적용 시 전체 a 태그에 대한 효과 적용으로 인한 건으로, a태그에 대한 스타일링을 어떻게 할 지 논의 후 진행 부탁드립니다.

**Comment by sunhpark42** [comment]
현재 색상으로 변경되는 건에 관해서는 우선 fontWeight: bold로 작업해 두었습니다. 더 나은 방향성이 있다면 공유 후 적용 부탁드려요:)
