### ISSUE TITLE
포스트 작성 기능 오류

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#85]
포스트 작성 시 에러 발생

![image](https://user-images.githubusercontent.com/46308949/120803948-104e0880-c57f-11eb-84af-743c3d2a83ea.png)

**Comment by sihyung92** [comment]
오류 원인 : 요청 내용 중 category 가 mission Id로 변경 됨

**Comment by gracefulBrown** [comment]
해결되었습니다
