### ISSUE TITLE
댓글 기능을 기획한다

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#915]

**Comment by Wishoon** [comment]
## 댓글 도메인에 대한 기능 아이디어

* 사용자 정보 제공 기능
* 댓글 CRUD 기능
  * 댓글을 추가로 불러오는 기능(페이지네이션, 무한 스크롤)
* 대댓글 CRUD 기능
* 댓글 공감(좋아요[네이버, 카카오], 이모지[Github]) 기능
* 사용자 테그 기능
* 사용자 태그 알림 기능(이메일, Slack 맨션)
* 내가 작성한 댓글의 목록 기능

## 댓글 도메인 아이디어 우선순위 선정

1. 댓글 CRUD 기능 + 사용자 정보 제공 기능(사용자 프로필)
2. 사용자 태그 + 알림 기능 or 대댓글 CRUD 기능
3. 댓글 공감 기능
4. 내가 작성한 댓글의 목록 기능 (프로필 페이지)
5. 댓글을 추가로 불러오는 기능(페이지네이션, 무한 스크롤)

## Task

* 프론트
  * 기존 피그마 시안 검토 및 수정 후 피드백

* 백엔드
  * 댓글 DB, Entity 구조 설계
  * 댓글 API 검토 및 명세

## 2주 1차 스프린트
 * 디자인 검토 (7월 13일, Slack으로 피드백)
 * DB 설계 (7월 13일 오프라인 회의)
 * API 설계 및 디자인 협의(7월 16일 오프라인 회의)
 * 기능 구현 (7월 17일 시작)

## 다음 회의
 * 7월 13일 수요일 백엔드 회의
 * 7일 16일 토요일 API 설계 및 디자인 회의 (12:30 ~ 14:00)

**Comment by Wishoon** [comment]
## 7.13 백엔드 회의

* 댓글 구현에 대한 검토
  * 안건 1
    * 댓글 Entity에 학습로그(Studylog)를 속성으로 포함할 것인가? `(@ManyToOne)`
    * 댓글 Entity에 회원(Member)를 속성으로 포함할 것인가? `(@ManyToOne)`
   * 안건 1에 대한 결론
     * 지금은 @ManyToOne으로 설계를 진행. 토요일 API 명세 회의 때 매핑 테이블을 둘지, id만 가져 간접참조로만 할지 최종 결정
     * 구성 요소
         ``` java
         id, member, studylog, content, isDeleted, createAt, updateAt 
         ```

* 디자인에 대한 검토
  * 안건 1
    * 디자인을 기획하면서 추가적으로 서버에서 고려해야 할 점이 있는지?
      * 아직 업음. 토요일 디자인 시안이 나오면 회의 때 최종 협의를 보는 것으로 결정

* 다음 회의 내용
   * 댓글 구성 요소에 대한 최종 회의 및 디자인 회의
   * API 설계 논의 및 댓글 Create 기능 구현 논의

**Comment by Yboyu0u** [comment]
# 7.16 전체 회의
- ## 디자인 검토 및 결정
   - 안건1
![image](https://user-images.githubusercontent.com/63579113/179340272-7cdc2c6c-de17-4ee9-b491-e0d844b0d002.png)

  - **안건2** 
![image](https://user-images.githubusercontent.com/63579113/179340291-ff5d4a5b-7718-4342-801d-673f3647b608.png)
### 2번안으로 결정! 

## API 설계 논의 
   1. CRUD API를 개발한다. 
   2. 예외 처리를 생각하고 예외 처리를 한다.  


   - ### 댓글 생성 POST api/studylog/{studylogId}/comments 
     Request
     header: Authorization: Bearer TOKEN 
     ```json 
     {
       "content": "암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용" 
    }
    ```

     Response 
     201 CREATED 

   - ### 댓글 전체 조회 (학습로그 한개에 대한) GET api/studylog/{studylogId}/comments 
   		* 댓글이 달린 순서로 (=오래된 순서)
   		* 최신순, 댓글 순 (추후 검토)
   Request
   ```JSON
	{
	 "data": [
        
          		 {
          			"id": 1
            		        "memberResponse": {
                   	        "id": 1
                   		"image": "http/~~~"
                   		...	
                    }
            		"content": "블라블라블라블라블라"
            		"createAt": "2022-07-24.."
          
         		  },
				  
		        {
          			"id": 2
            		        "memberResponse": {
                   	        "id": 2
                   		"image": "http/~~~"
                   		...	
                    }
            		"content": "블라블라블라블라블라"
            		"createAt": "2022-07-27.."
          
         		  }
        		.....
        
        
        	   ]	
      
      
	}
   
   ```
   
   Response 
   200 OK 
   
   
   - ### 댓글 수정 FETCH  api/studylog/{studylogId}/comments /{commentsId}
    Request 
    header: Authorization: Bearer TOKEN 
     ```json 
    {
      "content": "암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용내용내용내용암튼댓글내용" 
   }
     ```
     Response 
     204 NO CONTENT 

   - ### **댓글 삭제 DELETE  api/studylog/{studylogId}/comments /{commentsId}**
   
   	* 삭제 요청 시 boolean 값을 통해 삭제되었다는 것만 명시하고 db에서 삭제는 하지 않도록 한다.  
    	
  Response
 204 NO CONTENT 


## 개발 기간 논의 
- 프론트 
   - 2주 정도 소요 예상 (8월 7일 예정)
   - 1주차 UI 개발 
   - 2주차 백엔드 API 연동 
   - 3주차 코드 리뷰 기간 @ QA 
  
- 백엔드  
   - 16일 소요 예상 (7월 31일 예정) 
   - 7/16 ~ 7/26 API 개발 
   - 7/26~7/31 코드 리뷰 기간
