### ISSUE TITLE
글 가져오기 기능을 기획한다

### ISSUE THREAD

**Issue by gracefulBrown** [woowacourse/prolog#917]

**Comment by al-bur** [comment]
금일 회의 후 작성 예정입니다.

**Comment by al-bur** [comment]
# 논의 사항

- 코다와 타사 서비스의 글을 어떻게 가져올 수 있을까에 대한 회의를 진행한 후 아래 시나리오가 나오게 되었습니다.

> 1. 타겟 서비스(velog)의 rss 서비스를 활용하여 내용물을 가져온다.
> 2. 가져온 내용물을 prolog에 적용할 수 있도록 전처리한다.
> 3. 전처리한 내용물을 등록하는 POST 요청을 보낸다.
> 4. 이후에는, 등록한 게시물을 prolog에서 직접 수정할 수 있도록 한다.


### 이슈

현재, 여러 이슈들이 있어 공유합니다.

1. 현재 시나리오대로 진행되면, 백엔드(3기 코다)가 할 일이 많이 없는 상황입니다.
=> 백엔드의 역할을 더 찾아 보거나 다른 방안을 생각해볼 예정입니다.

2. velog의 rss 서비스가 사용자의 모든 글을 가져오지 못하는 상황입니다.
=> 현재, tistory의 rss 서비스에 대해서 찾아보는 중이고, rss를 활용하지 않고 글을 가져올 수 있는 방법을 조사중입니다.

### 앞으로의 계획

7월 18일 활성화 스쿼드 정기회의와 코다와 회의를 진행한 후 위 두 가지 이슈에 대한 앞으로의 방향을 최대한 빠르게 정하고 기능을 구현할 예정입니다.

**Comment by al-bur** [comment]
# 이슈에 대한 개선 사항

> velog의 rss 서비스가 사용자의 모든 글을 가져오지 못하는 상황입니다.
=> 현재, tistory의 rss 서비스에 대해서 찾아보는 중이고, rss를 활용하지 않고 글을 가져올 수 있는 방법을 조사중입니다.
=> tistory의 rss 또한 최대 50개의 글 한정인 것을 확인하였습니다.

- 유저들이 작성한 블로그 글을 보여주는 것이 목표이기 때문에, 단순히 아래 사진처럼 링크를 입력하면 글을 보여주는 방식으로 먼저 해보는 것도 좋을 것 같습니다.

![예시](https://user-images.githubusercontent.com/64825713/180715030-720413cb-c7f6-4f23-bb55-da755a66870e.png)

**Comment by al-bur** [comment]
# 글 가져오기 서비스 기능 설문 기획 및 진행

## 배경
- 글 가져오기 서비스를 위해 여러 아이디어가 나왔지만, 아직까지는 실효성 있는 아이디어가 나오지 않았습니다.
- 기획에 계속 난항이 생기고 있어, 타겟 유저들에게 직접 설문을 진행해서 방향을 다시 잡고자 합니다.

## 설문 작성
- 설문을 작성하면서, 중점을 둔 점들이 여러개 있었습니다.
    - 친절한 설문인가?
        - 친절하면 친절할수록 원하는 질문들에 대한 답을 얻을 수 있습니다. 애매모호하게 질문을 하면 모호한 답을 받을 수밖에 없습니다.
    - 빠르게 끝나는 설문인가?
        - 보상 없는 설문이기 때문에, 오래 걸리는 설문이라면 아무도 하려는 사람이 없을 것 같았습니다.
        - 최대한 간결하게 질문하고 원하는 정보들을 얻으려 했습니다.
    - 원하는 것들이 다 담겨있는가?
        - 짧고, 친절한 설문을 만들려고 함과 동시에 원하는 것들을 미리 파악을 했습니다. 아래는 이번 설문에서 얻고자 하는 것들입니다.
            - 글 가져오는 이유
            - 글 가져오는 방법
            - 글 가져올 때 불편한 점
- 추가적으로, 사람들이 많이 응답해주는 시간대에 링크를 공유하려고 기획했습니다.
    - 아래의 후보들 중에서, 다들 slack을 보고 있으면서, 바쁘지 않은 9시 45분에 올리기로 했습니다.
        - 오전
        - 점심
        - 저녁
        - 늦저녁

## 설문 링크
https://forms.gle/vspvATGdKaxPCN7r8

## 결과

추후 공유 예정

**Comment by al-bur** [comment]
# 글 가져오기 서비스 기능 설문 후 방향성에 대한 회의 (with 브라운)

## 회의 주제
- 이틀 동안 진행되었던 [설문](https://forms.gle/vspvATGdKaxPCN7r8)의 결과를 바탕으로 추후 `글 가져오기 서비스 기능`의 방향성에 대해서 브라운과 논의를 하였습니다.

## 회의 내용
- 설문의 내용을 정리해보면 다음과 같습니다.
    -  타사 서비스에서 작성한 글을 가져오는 대부분의 크루들은 본문 내용을 복사해서 프롤로그에 붙여넣기 합니다.
    -  글을 가져올 때 불편했던 점들의 대다수는 마크다운에 관련된 이야기였습니다. (티스토리에서 기본모드 => 마크다운으로 전환할 때, 애초에 마크다운 문법이 제대로 작동하지 않는 것을 확인했습니다. 하지만, velog는 애초에 마크다운 기반으로 글을 작성하기 때문에, 프롤로그로 가져올 때는 거의 완벽하게 가져와지는 것을 확인했습니다)
    - 결론적으로, 글 가져오기에 대한 불편함이 그렇게 크지 않았고, 존재하는 마크다운에 대한 불편함은 대개 타사서비스에서 완전하지 못한 마크다운으로 인해 발생된 문제였습니다.


## 결론
- 글 가져오기 서비스 기능은 사용자 니즈의 부족으로 인해 더 이상 진행하지 않기로 함.

**Comment by al-bur** [comment]
글 가져오기 서비스 기능은 사용자 니즈의 부족으로 인해 더 이상 진행하지 않기로 하여 issue close합니다.
