### ISSUE TITLE
학습로그 글쓰기 화면 변경 - 글 작성 시점에 역량을 맵핑할 수 있다

### ISSUE THREAD

**Issue by seokhongkim** [woowacourse/prolog#924]

**Comment by wonsss** [comment]
## 7.18 진행상황
- 학습로그 글쓰기 화면 사이드바에 역량 매핑 기능 추가
- CSS 스타일 등 수정 필요
- 수정된 API 연결 테스트 필요

[수정한 예시화면]
<img width="584" alt="스크린샷 2022-07-18 오후 3 05 53" src="https://user-images.githubusercontent.com/59413128/179453358-8c8a9930-ed2a-4135-8e82-6eaca762d668.png">
<img width="590" alt="스크린샷 2022-07-18 오후 3 06 00" src="https://user-images.githubusercontent.com/59413128/179453368-06d2cad9-ea97-498e-b82b-a1fa4130df79.png">

**Comment by wonsss** [comment]
[제안] 작성된 학습로그 글 화면에 매핑된 역량을 표시하면 어떨까요?

**Comment by JUDONGHYEOK** [comment]
## 0725 중간 진행상황
- 각종 스타일 수정
    - 사이드바 요소간 간격 조절
    - 모달창 위치 조절
    - 역량 선택 플러스 버튼 스타일 조정
    - 역량 요소 간 간격 조절
- 검색 기능 추가
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/65863017/180792606-53fb2c06-3667-458a-967e-f717acce8218.png">
<img width="242" alt="스크린샷 2022-07-25 오후 10 47 07" src="https://user-images.githubusercontent.com/65863017/180792685-6fb1451a-2ced-426c-b99f-9b77e2cce036.png">

**Comment by wonsss** [comment]
- 검색기능 추가 등 스타일 조정
![ability-mapping](https://user-images.githubusercontent.com/59413128/182066773-b4ee9b4f-5db4-43f7-8165-eccda7e709f7.gif)
