### ISSUE TITLE
에러 채널

### ISSUE THREAD

**Issue by pocojang** [woowacourse/prolog#933]

**Comment by qhals321** [comment]
2022-07-20 (수)

Summary
- 회의 내용 : 현재 인프라 상황 공유 및 모니터링 관련 키워드 정리

- 이번 목표 : 로그 대시보드를 구축한다. (다른 대시보드는 나중에!)

- 현상황 : 확인할 수 있는 로그 레벨은 error 밖에 없다. (다른 로그 레벨을 확인하는 것이 힘들다.)

- 할 일 : 07월 25일 (월) 까지 키워드 관련 조사 이후 공유

- 관련 링크 : https://miro.com/app/board/uXjVOks6AAs=/
