### ISSUE TITLE
배치 프로세스

### ISSUE THREAD

**Issue by pocojang** [woowacourse/prolog#934]

**Comment by bperhaps** [comment]
- 배치 챕터를 통해 우리가 얻어가야 할 것.
  - 문서만 보고도 배치를 작성할 수 있어야 한다 -> 문서를 < 코치님들
  - 이론보다는 실습위주 -> [이 PR](https://github.com/woowacourse/prolog/pull/935/files#diff-05badc177c06b326e4bf821b2d741ab15d34784e6205a1ccec392f3aa836522c) 를 이해할 수 있다.

- 이스트
  - 손너잘 의견에 동의
- 에덴
  - 배치에 대해서 잘 모른다.
  - 경험이 목적
- 이브
  - 개념은 안다.
  - 일괄처리를 한다정도의 개념
  - 경험을 통해 배치에 대한 흐름의 경험을 얻어가고싶다.
- 베루스
  - 써봤다 정도.

---

## 공통
- 경험을 하고싶다.

## 목표
- 간단한 개념 강의 (약 30분?) -> 손너잘 준비
- 학습테스트를 통한 배치 코드 작성 경험
- 최종적으로 챕터 인원들이 작성한 배치 코드를 프롤로그에 적용한다.

**Comment by bperhaps** [comment]
- 배치 로직



- step (하나의 책임)
 -> item reader
 -> item processor
 -> item writer


1번째 step
-> 모든 레거시 인기 게시물을 제거한다.
1. tasklet 으로 처리한다.
2. chunk 프로세스로 처리한다.
  
---
*item reader*
모든 인기 게시물을 가져온다.
---
*item processor*
모든 인기 게시물을 delete한다 (soft delete)
---
*item writer*
상태를 저장한다.


2번째 step
---

*itme reader*
-> 프론트 엔드의 1주일간 인기있는 N개 만큼 게시물을 가져온다.
-> 백엔드의 1주일간 인기있는 N개 게시물을 가져온다.
  -> 단 1주일안에 N개의 게시물이 없다면 그 전 주 데이터를 계속해서 가져온다.
---
*item processor*
-> 가져온 데이터들을 PopularStudylog entity로 변환한다.
---
*item writer*
-> popularStudylogRepository 저장한다.
